---
apiVersion: db.movetokube.com/v1alpha1
kind: Postgres
metadata:
  name: bookorbit-main
  annotations:
    postgres.db.movetokube.com/instance: postgres17-rw
spec:
  database: bookorbit
  dropOnDelete: false
  masterRole: bookorbit
  extensions:
    - vector
