apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: mautrix-whatsapp-sopssecret
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:CCAsCuvlns3uOlT4gegJEGFvl+2Riv4=,iv:bo9Blq+guhS+M8i7TqQ33C+wicRnZUj9jpf8Tz8i5eM=,tag:UQ+TRXBlUv0nAFyoFiLJ0w==,type:str]
          stringData:
            BRIDGE_ENCRYPTION__PICKLE_KEY: ENC[AES256_GCM,data:GcCyhzsHW6uoUc7dh+2b4CVenI5PHZnEAfxlvDuXZrpHNyLQEAzXGj6VqNPP0oBkMo9GRRiVZqFpVV0BnN34uw==,iv:FrSxhzhaK1ZbklZofAdU3/Giwk9ZBWrHcs/uXa7L/Fk=,tag:A2Gctio+hfgLp1iQ+Gwbgg==,type:str]
            BRIDGE_PROVISIONING__SHARED_SECRET: ENC[AES256_GCM,data:YOA3dt7BbScmJBwfM2pdKsZkbZp9ZIplk0Nn6zvugyYMDhtCzwXxXa78nZKzh080UNV18wdi+3AaTJQIaSyW+khnuTZKi//W0kU4MSL72djCp+c0YBv/bPD4WA6ZKiY7ELRfCb9HHjJZFLvuEz8bFDXIogm9vl7vqldeo2npUlo=,iv:a3s6ZBeWtUKxeOurzrMdOfeZZiLr1i/fRLck+It0/Mo=,tag:Jjxa2lUHvSTqJ7dUbrtAuw==,type:str]
            BRIDGE_DOUBLE_PUPPET__SECRETS__G4V__DEV: ENC[AES256_GCM,data:vuLBiP55QmEGX+uT/Sy9JsJNJtjlvik+4msHn039hkvHdheGXvFiUA6MFiZKSaJmdkRNnK+jK5FdLds/L7yUEN4dQqOwpT9dkA==,iv:url/FPc0t59Ba3QunlQtidj6avn3euvRI5A04zHwQVs=,tag:djRTvn6Eu2FByAjyDqfJGQ==,type:str]
            BRIDGE_APPSERVICE__AS_TOKEN: ENC[AES256_GCM,data:WDiNN0J3oWM3QMGkxep4U65HAMA9JwkqbkFrk+8ubx2KEbA8xE2zBjwZJuhK/B+Qu7pCaBA2r+DvOnHPq+lPTA==,iv:VgTbfUvvN1M98z263gkgKhrHEpglIImtDV26iqSCBNI=,tag:0mi8/2MoHv1PvILXZXjcBg==,type:str]
            BRIDGE_APPSERVICE__HS_TOKEN: ENC[AES256_GCM,data:a7Q9xLJ1zYoaNr+5dial+2vvDp66D8qNYjY8C5bKDvExqgw4x+7D2pdGFmQSP7d23Noc3ZdfDvLeKwlKZaHofA==,iv:mo6Ei70W94lx1BptRTbSzx8G6R9IrltKHG99NbUT6J0=,tag:UoeVdZYbT0QkEmMsSrpDWg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSDY5QTNIZ0VNcEJWeHYv
            OXdiRXdQdWhySWs5WXJUL1lrQTY3ZW9xS3hNCk94NFpTOWJ1VWl4Z3F3eTZqZTVw
            TjhKRG5Wdk5DbzlPTmZZWGtCQ0llSkkKLS0tIGZzV1piVUVud0U2WUxSZHVwMHVO
            MURGQVVidXczOFNhODRvODB3WnBFZjAKPaGjwsLSW4ZOnzmV9r3bkpFDGSZH4W5M
            uLlZNpajjZmRNAoGJspE0pKHAFoRxXs8g1qQiAwNroCyNZXtNB6tXg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vqm5gwkmf38jsmt3j4lm3fdslausskaadtz360ewn0g7z2fchahqyr694v
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5TDdZQ0M4VmpSaTRuN3pT
            cnFBZGxzRVc5VU5lRFk3SWVlcXBkR3VuQWw4CnlZSUZzRGJBOWcwR3I4cVQrdCtW
            THp6VUllRTZjZWcySVZqZTNhcFhSajgKLS0tIFBzQ0E2NVdQZWEvamxIdFAyc2pI
            Z1hzV1NzcDYyWUgvQlhkcWcxeUU5U0UKheYBoNXsV1xTzb/6WUwOXPCEVyJgj9vR
            aTAvnUPHQICLZyCHwhOuQzRwBRDl/XB2HYT5AC+BG3HmbspSIX7dyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1aqel4n2xyfjmzjgey0mhxzhlmg2qd7xusjweku4w8u94dsq2gpmqye3wus
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4QzlxVTkva1QxRGd1M0lG
            QnVzaytxb1FoUW1XelpVeWxyYWV4cm9SNjNJCjFncXErbGZ4a1RxeFJMOUF4WTBj
            b1JnSHZxUEc2WFR2NThrWTVraEljUVUKLS0tIGQyTjNONVlFSm9QUUxOMGpaakpi
            UkRZU3BmM2NzOUtDQndBWjZLVkpDVkEKeSqxrwDKh53MlmomP+E0/j5IIYkx1saC
            ZUH7lE2pvMVXMZmP8M4hIR6rdTeKvLrjKdCHtXVStlUJLvi/70YG7A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y562y0u4k8y0eyq56s4g00ssd2cduamddcgfpu8fs7t00pfjss2s9nymt8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMGpYbEFlaHlzU21aVlZF
            YVNCV0FBVFJkWit2c0ZrbUMxSUVpVkc1RjNRClh4dUl3TmIrYkp4RUxqajhqTmVF
            UTEwOUhJRjgzMmlxdUdMN0oxK3J6NDQKLS0tIGZWNXc2d05NaWY1ZDQrU1VXdDhu
            WkdJVks3aEZxcEtwSGUrRVd1YjdGeTQK6/nCB26zX2PMiV+QiDpFoU3BOO7k/9Z7
            fUuX8lpyIsPvnhhxCDvbcvTm7QhSypa96r9f2joCYfMxELeHv8TD6g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lv53trxftjem0a4hewf9h9dmp65cql6ycaj5q8kvfnfspccg747s6lxpxg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJaE5TWDNvWDlmSStISkhJ
            K25tT0I5VzB0VzJ4Y0lsMmRjbGVxU3MxV1NrCnRiYmpmWUxBZDk5WEVXL2lyZ1Jy
            WHBKMnRnemVvc0RXSkdiZVprVEJVUGcKLS0tIE05Y25HZUFQKy9XaENhcUU0OFln
            UTR3d2pMdjFqWmRWeTFKRjZ2TGNmS28K2/Eu2YRK/Dgw/lbLLo97/rGcSHOm/ZAl
            L7uzx/Q6MNwemiXM57tNjLvq57zJVgJfDsVqGZ7ewLL+osRX8t+eaw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17ryqtmnakl6rc3z6qpqkhmw5pnsnzy2arwv7ecnh3ayf0za5pgtqft7lcn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGt0aTNnZyBZSTRu
            cUR6WXJNUjdYcUtVN1NqaHR3Slpta2QzOVB2QW5sTHIxYldpaFdBCnhpRnc1UEhO
            dXNPbmhFTTBrZVR6VHllempFYkdEVFJNRjlkbjRvQnZiSk0KLS0tIDNDeDdoamZS
            Ykh1Y1F2dERKbkRkcGYrYTZoM21meUxNeFd6N2tXZCtaY2cKi0n2obPhNk2dJHM/
            2eHXTsUvT1s+gPewtjQY9P0ysFyD3oBNWh4r/AkklzZGXf9yc5J6imBQuC88tg61
            xLYAKg==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFB0EXmaOVc61axVxDoWw1Y7JypG4LFFbS6+96dFY2VS
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Uk9XeUZvUkF3NHptdW1L
            b1E0TzhNaUNUNVBZKzQ2c2VTYXEyTHBOVGlzCnhsV1h2dmNzeDBjcm5ZRjhQWXcx
            L3MySXdYY3h4STdyNHBjUmxnYnVsS1UKLS0tIGFIMVp3Q3RxRGVPV015STVldXk5
            WlorUnI5Mi82K0tKcTNQVGVaQTVRV2cK7Q+AgMx/RPekjPjixyUI/X3Yys3DBxie
            gHhhVKEO5XFVT07sfjTyGan2t00VC3X15FsFVmYdVFt8MfQQNLxO1w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age179mmzgpy7ldyh3w6zld9vxjegxv80mkt6kffgg5enyquqrwnspkqv7sq7v
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzeFU2ZE1uZ0JYOGxMazRS
            ODM0UWdSNXAwZkthSTdWYStVZnE1eDZld0VZCkpJbERRU29lc25XbEhKSklKUFlZ
            dlZvTjNXalBjWGV1dFRsSGRJdWxoYlkKLS0tIFN6WTRWS1hhckFzeHJ3V2M3ODIw
            MEpGeVU3b24wQ2xiVm1BcnhWaTRWSG8KJzqVPS2+9z2RXeBEoKlEOAeAardbKveZ
            77At0XvopGJuDw0P3bARmNz2MkB0kJIejBZerGHBchu3pgUkG2/yHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k63d5ts2w8hfvdar7lan2qamhcgrjpfdv4um97q0ehjs553x4sysx08xcg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxM2NRcXVqbE4rd3hlU01m
            aXhDOGErQnpHU3RzTVkyWnNNUlJnVUJkeDE0ClVVQ3BEempEMjdJNDRMcFhDRjFS
            amJkN01Ca2gxckNNanh5L1BQcmVCNW8KLS0tIDF1bHlZT0VtKzNJT2k4YU50bWVR
            Zkl3aTdSbUZjV29kdWo5QkhDR00wNXMKgLrMng6Yu/9DXYxs2pKwDYT5ZW0WVMoc
            T0oiOq39aHNIQlBEle9PKa9XkoTyGyoyiILL5tkA9VJYeUTeZEzBcg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mkkltp58ptsvn5t7x8anr4hy20z0z6568nsljfa7tmwx07ug09aqf6rxe6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNE0zSjI3cldrY1ZsbEJC
            QkpQV2Q5Nlh2MXdtYkExRlZuVWRjWEl0VkVBCkhtZHc2bFJWcXpsb2lodktFZXhi
            Vi9EcGoyUTJ2U1BNd3BMb0UrQ212ejAKLS0tIDg1ZXdQbUVRREV2NnBzSW0wZ21S
            QVFsNUp0Q0xCOUxFL0xDc3J2c2lFeWsK1lqQpeHMYAJMW85dK82vkt/jUme9Mt73
            MIYGEDYILxnemgy/vDn+emWc14hot7tpRBX233GOXG5bbwVI72Szog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tfj0kfd2twsa655d5hx2afczlpcfzw7hapc07gr7ywnqq08qxdtsud2gfz
    encrypted_suffix: Templates
    lastmodified: "2026-05-22T04:32:59Z"
    mac: ENC[AES256_GCM,data:cfNkrRZ6OkcBIZ8O5kh28WXLUQfGbVQXhTmrIJJWHc7o0X8fjyqJZ4vRz4nNN+jnvnvFUexXzaePB924WJrnHpkko+e62FWb1uLt2blqlwkY+4U4ppMfWa2Ts7naQANqwtveZfzoX1/JmiERd79jOxFihS+4o74C+AE37RUK4eU=,iv:aSTBzmTLgvBkowphn1o0tctOYM/6K29Q6K2MI/ds2W8=,tag:HrwPXQPvPwZ2J+AW6rEn4A==,type:str]
    version: 3.13.1
