controllers:
  proxy:
    strategy: RollingUpdate
    containers:
      main:
        image:
          repository: ghcr.io/ryanbekhen/nanoproxy
          tag: 0.17.3
        env:
          ADDR: ":1080"
          ADDR_HTTP: ":8080"
          NO_AUTH_MODE: "true"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
            add: ["NET_ADMIN"]
        resources:
          requests:
            cpu: 10m
            memory: 512Mi
          limits:
            memory: 512Mi
        probes:
          liveness:
            enabled: false
          readiness:
            enabled: false
          startup:
            enabled: false
service:
  socks5:
    forceRename: nanoproxy
    controller: proxy
    type: LoadBalancer
    loadBalancerClass: tailscale
    annotations:
      tailscale.com/hostname: nanoproxy
    ports:
      socks5:
        port: 1080
        protocol: TCP
      http:
        port: 8080
        protocol: TCP
