apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: tranquil-pds
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:KIDJOSAbenIFTG+y,iv:xlcr+AHqrJQxXhM0huo1q341f65UL6neddxZEpNhdFM=,tag:Fpk5zAi270pxLmUnVopM7A==,type:str]
          stringData:
            JWT_SECRET: ENC[AES256_GCM,data:q8Y07L4Xva/MNxJcGEl+EjZFrZEsPd/6729PYkh2YOqKOI6j8M7FfD0BtONZG0JWX43ikOS3E33Ws5bUkTAZeg==,iv:sFcX5+Ry2QEYw5Sk9aiNgMem4Tw6Rs/E1jHkHh5oLfc=,tag:sGKg+VvT7HSxvh5lVNbrUQ==,type:str]
            DPOP_SECRET: ENC[AES256_GCM,data:d2iKf9jmVzARLOjkvq8DzQNhNyg7W40hX1Ym6y6DkDBBJ1zF/HAYjPkH45yLUum2OhJnlqqnBxnzCnA+4w64Nw==,iv:+KmNMvbFohsJCzJkuSAl+pTvaaxr0JwS5LnKolhitAc=,tag:xEDjipm2d1cC9YyF14uSpg==,type:str]
            MASTER_KEY: ENC[AES256_GCM,data:6/xeM/sa5WI5kKxKudfA3iMkeZtSKceEg8Nc9cVzN+fiymFeYZGF8K5FnbSJwb2o7Hc5ka7x+SFBOXJ8R0TvXg==,iv:0oMEfFnei3fdc89tki0yhE0vHMR/pik3TnwoIXJy48o=,tag:UyeE/lXZ+p1bFURksD4u/Q==,type:str]
            SSO_OIDC_CLIENT_ID: ENC[AES256_GCM,data:8NZT0S0cQdCIMYcuVJ0wK89/Cilwde+r0eQWzxqc5Nh5ANfMfx2EWA==,iv:lqZ3zocLXCJVc45MumIRenxz5LP/X0pnTYIXDKmBPZI=,tag:UQOUqkkF4SoRmFekvdt1cA==,type:str]
            SSO_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:q0aYx5zuvepIrWWf3zhTAu3VNblvqWvzw3EXW6Km/x3fRJqWomgSxOnQwK8dKAYhzEP01VU0IKzyQwFgZx0sUNIZAvyF/SxHs1clfjsKU1Com6fgeEFZKvXEtNcuglw3ip7AitVvGMKOTmdlhywmVAB0hC3m4axkRugnq2WzOS8=,iv:RrmaMJOpKv2dmqtD6SSDzSxG2EVD2d5R1r4hhkwWgPI=,tag:Lg2y1LyEM6oizyG5iC/ohg==,type:str]
            SSO_OIDC_ISSUER: ENC[AES256_GCM,data:zGkZWHTDhNGu1gYVe2CTCdZn0E6y0lSX9LaDa0nh5LQQLXnLf8Qtc7vVdNszPIf1,iv:Hs9ymePQTvuiN5wMUWardWr3XBRucvW/2AULaOUTqCA=,tag:Ts/LYGiWnGLbeM2jK17pRw==,type:str]
            S3_ENDPOINT: ENC[AES256_GCM,data:ut4Rsga+miR17haDXUtxgh1VUtqhBr9DVKm/qPWD3PlIJYs=,iv:M/4BiLDy/6SJL6DaLuFnoaLt/0r/Bbi+Qw+TH8PCJuY=,tag:YwplU9dSt4m+lxzMfzXZzQ==,type:str]
            S3_BUCKET: ENC[AES256_GCM,data:TVQel9ulwT7FK8esUHuz5cf4IHs=,iv:9y8mKNayDDoPqBOShijz6avSDtPZHq/KpMuYVlZ/Ymg=,tag:VpZ11lqVrGIDk6g3u9/V1Q==,type:str]
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:sFsglMbsVR2zj4s6au5sJb0xvMw=,iv:yPow4xLP7mnWL4lK99YJAnll09l7OCykDCbRzLNHd8o=,tag:1Le3nvwoh4KkAUGYSRiANA==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:PI92/xxrI8OfdJPK/XTgvD02zWpU6zvtpaOwlO807JbPWRWaqfQtLjv1wg==,iv:qyNUflv+cr5k3w6UlBOS42q5iIlj6azxhen1JMOfhKU=,tag:tdd7cZnzpGfvXwPiTI3evg==,type:str]
            AWS_DEFAULT_REGION: ENC[AES256_GCM,data:1NdTwA==,iv:bho9ieHWzU/ETyMs5RiKSNZcsEm6qmdKBoB6xr3HG/U=,tag:gdvw+lorVuN9QIO+wldcZg==,type:str]
            AWS_BUCKET: ENC[AES256_GCM,data:8WYBhVk6uhCcUp6tWpKebpt+SeE=,iv:CeM9SCG3N6fcmT67ER7HXUMfzqf0ycVQf5WC8f6BjH4=,tag:IErB7NRabG+XpV5BMpKeNA==,type:str]
            AWS_URL: ENC[AES256_GCM,data:6QfUjHAss6LkZlfXOJX2UwQpJWOO1jflAOQnw7yPgmvvsNUDLEUv7Kcb2MeWQufjnun8Zoyl2rA=,iv:XYhcL2/pNCuI7TfNE1s9Yr1xRG57IDAeqNEXozXk5yk=,tag:AwvxlU36SY1I9AMRQgiKzQ==,type:str]
            AWS_ENDPOINT: ENC[AES256_GCM,data:LHEC+1JLay5DCv+PhOoWDBraB/xEI+FPRsCRyoIQmhsb8iQ=,iv:i4QTXm2b7QIemPRfxN6fi1G9cy0B4fSoL8woqIn6n14=,tag:fMkB0fX7bdf9sOr6rNr3Mg==,type:str]
            AWS_USE_PATH_STYLE_ENDPOINT: ENC[AES256_GCM,data:64yEPg==,iv:k01Imo9FVOPDAz8ArOSiTdOaKzvPe+SwmSmQfDn1tpo=,tag:L8wvcjlZJYbXGFKGXK1LQA==,type:str]
sops:
    age:
        - recipient: age1vqm5gwkmf38jsmt3j4lm3fdslausskaadtz360ewn0g7z2fchahqyr694v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicEw0TlF4ekZvYy9ncnJu
            ZkZIV2lLSk92Y09oRVNPU3pMZC9nMzFyekNNCnBnRVZBT2cxcXREVGdHMmRrdFJ1
            UDhPL0VlaXVOTEpuTTVGLzErNWRGOFEKLS0tIHByUEZTbUJNcnA2amltck1zWWp4
            M01Cbkg3SnF0OTVZWG9QS1c3bENNRDQKq9ThB0G9dZOHiyJHZPvy6P41qDpa5xNe
            oW7tRVyoxjlJqsJtg4vVeKsnQQEfQZ1zN/J0jrs1cjqzxLPMYKDi0w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1aqel4n2xyfjmzjgey0mhxzhlmg2qd7xusjweku4w8u94dsq2gpmqye3wus
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqd21yL1NsZVZyVlkweTJM
            aE5wOGNvWTNJMWdYaTJYNnRmQi9WTXBEbW5vCkJrNHhzVTJMbnVEUlU2MVRYbVgz
            WlBFRkNwa3pDQVRsbWRWODF1VUtVem8KLS0tIFQvaDZBYy9kczh0MllOMi94YWZP
            MHI2WkFNMEYzWHRSa0xFeTBPNHlIL0UKGw8Q/ebh38HNkglyKKVFVzfSbZvvM/UC
            Fsox9urJaj3mWoFRgW8hy1MtNpNgYSAD09w6I2mbrDS+Xpp0FHgX5Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y562y0u4k8y0eyq56s4g00ssd2cduamddcgfpu8fs7t00pfjss2s9nymt8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMV096QVdVNGtlazNiQjlq
            VEIrUE9TVEdRZ0pVUURmZ2phSXFxcldNblJvCkUzQkxMRnBkRUo3N0pKVzhSRmY3
            RGF5NjlBaG4vWkxIRHZtVlVOWXNQU2sKLS0tIGVUak9RWEFuSXVabkhxb0h5MWNq
            L0MrNjA1NlFWQW1KQ0Fuek10VC84bncKAXctf7jFJ7RkpzDadG20QLv7GrZaQZva
            6gXSlT05EUm/kGYKErpnegOlLHH7GvuE/vVn1SCV9hfqdUfhY7MG1g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lv53trxftjem0a4hewf9h9dmp65cql6ycaj5q8kvfnfspccg747s6lxpxg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwYjJJVFNSZDJjZ2FyZitW
            eXNicHMzYTIzK1lvQnNTVGV0dXNraEtkdFFJCjZqY3VCQ1FTMGYzZmxObStDblZD
            OCtIdHBZOFNUbHp0TFBzMkNpSG85M3MKLS0tIHVrSFdLN2Z0b3duTENxZXVQZzBL
            c0NrbEQ4RjJ3SzRXZ1ZEUzRkeWluQnMKAyc6HwOELfkhD6hJY63GAMjR+gIpJ5b8
            UJ6HL0bwZBqPPTsdCYVgFLs1CsilSrZirzKrsFmyyn7MryPMLqA+Wg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ryqtmnakl6rc3z6qpqkhmw5pnsnzy2arwv7ecnh3ayf0za5pgtqft7lcn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjT3EvZE9lcmZEa1JVZ3BV
            TzkxL05zbzFsc1Azeld2YkdUR0lCcVJpeG1JCjVsUDdEaFREMGFpemFWd21EUzEy
            b1dPNlQwakVIWmNSNzJsblZsRExxNjAKLS0tIFdCR09xeVc5Uk1oVkY0MVIzZ3NP
            SkNNVUxkeldpTGVvbW1Hd0VVQWZXaU0K8cXD1oz8Nq++i2+TkksbplqRj1PHJYyu
            0Q55RQWQvhxLjgL4GGrM3zAYPT+7QQL2ZC8Ypou8Q837py9lQ8gUGA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFB0EXmaOVc61axVxDoWw1Y7JypG4LFFbS6+96dFY2VS
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGt0aTNnZyBGdVBY
            Y2pHTGRSYzdnUGpoMkVhTzl2Yzl5RU1uTE0xL3JBWno5VTVOT21ZClU2M3k2TVUy
            cUpSb2xHTUZ4Z3VJVUZtdys2bDhaaHR6TEJscHV3VFJDZkEKLS0tIDVaMFNBMm5p
            NktlVVZHRHh4Sml2UHA0N1Q4dEFzdEFsOUx4bUJFQWNxTDgKrHh4uyFfrL1pTDaA
            HwKkAIhAgEer7H6L/VEai+3/BjmZKGl56rPYapRPixiH6A50w6Ts7izpybKPvDMA
            4OUg4w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age179mmzgpy7ldyh3w6zld9vxjegxv80mkt6kffgg5enyquqrwnspkqv7sq7v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAza2V5VDdMd3pxTy9mbG5Z
            eUFEUzMyS2RxSUsvWS9KWlNyS3BtdmR1YUMwCmRkN3N6OFZnZVczM216cTVBV1JZ
            MEx4YlM4TmpEV0lRdFNibWNvWkhpaDgKLS0tIG5Ddno5dzQvYkt2YVMwekdqbjVR
            V1RTa3VRSWJ2UkVnUnp0cGtVWW5zOXcK3tKnKg8+C2icoFNi16t5e9kV76jE14hu
            s3UwcHPbG3S2lQCbSfELV+fjU6M1PHj+X8+wTU8pqisMW91Cs1XQYw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k63d5ts2w8hfvdar7lan2qamhcgrjpfdv4um97q0ehjs553x4sysx08xcg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUFRNMHRucVU3bnFBT2dy
            d1RJcEIrZzY2VldJZzlMcitodG5keThDdkNnClFsM0w5RFpYMmc4VTJHczc2ckpF
            eVdsdUFZUHpqbXhLWVpDNTZ2N2Era2sKLS0tIGZGcVlpZFh6d2ZjZzJXWG9kejVJ
            THlCM0wxRGYxak14TW9QTWswdFpEcmcK3mh/Q8vy7IgiQNqwyY0E5ALjha/2IzjF
            NKzMFMyADn7wOnV4WqwP7RIHZBD8AUEv1LbiresAoaF/nJZlSin6EQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mkkltp58ptsvn5t7x8anr4hy20z0z6568nsljfa7tmwx07ug09aqf6rxe6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBia3lEM3VqWDdFYUVxRkhr
            YlpwSjdZMkNoK1JVRlAxcjAvSDVSSWJCb1dvCjMzYi81aWFnSVFwZCt2SFlCdXVQ
            SU5wZTJIYjNBMVhuN2kxdjlBZHBPQUUKLS0tIHZiV3VZT0s3ZW9UcUJuZU1hMHdx
            ZzhEOW52WmY1UzB0NHY0Y0dXTUYwVTQKNFNUJfDXB0WgF7kg0vtPPcqgDjyUmN9b
            44ZZxSzGjZN0We2l+IqOgQm7UhD0HcK+VjE64+hDX1M4u286OBzB7w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tfj0kfd2twsa655d5hx2afczlpcfzw7hapc07gr7ywnqq08qxdtsud2gfz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZlQ2bUxObStLSmNuNGh6
            bVpRYktMLzNEZWpkR3F1T25Wb0c3T05ZY0VFCnZOL3BCTGRZUHhQb1lKM0V5ZHhv
            dlZJZjJCQXpvT2FSQnNlL25xemNFODgKLS0tIEdqTVBTR2RML25GSFhHb3IzdStO
            MVlUUVhURDFhbitheGpCZUVZcGJkZWcKYx/TI/Pt4OH2t2b2v/M5SrZ21Gp1frDC
            OUCY/aT6GuGSE9RpDFLLLsBdSRQ39709aRL8bJYuXtGIBbh/Uuby4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T22:10:15Z"
    mac: ENC[AES256_GCM,data:5TiJ3a9rC0DtptEpIxoyaIDf2GprZ9J14nVxS7xlUTQd5iXXaTc8ljmFjdOAxh3LR3iczlluYmPgqv+LOoa150VZz2BXjgqpUWXiHHMIQT/4RXJ3admHFDmy722XxUg6gkyeEMPhmxevigN0A4sU6V/By36q5YjG0wLi4yoG/ik=,iv:HDPHz6mBP9tob8Q0jw+eAwl4DFObu0Z/a0MpNDdK6t4=,tag:1AkMvW8c0p8qbyizsjB2aw==,type:str]
    encrypted_suffix: Templates
    version: 3.12.2
