# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/library/common/values.schema.json
controllers:
  main:
    replicas: 1
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      main:
        image:
          repository: docker.io/excalidraw/excalidraw
          tag: latest@sha256:4542f30bea392b833822d0e7db4fa2220e6706ca962c082add2665159fa91758
        env:
          TZ: America/Vancouver
service:
  main:
    controller: main
    ports:
      http:
        port: 80
route:
  main:
    enabled: true
    parentRefs:
      - name: http-gateway
        namespace: envoy-gateway
        sectionName: https
    hostnames:
      - "draw.g4v.dev"
    rules:
      - matches:
        - path:
            type: PathPrefix
            value: /
        backendRefs:
          - identifier: main
            port: http
