---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/library/common/values.schema.json
controllers:
  main:
    replicas: 1
    annotations:
      reloader.stakater.com/auto: 'true'
    containers:
      main:
        image:
          repository: ghcr.io/bookorbit/bookorbit
          tag: 2.5.0
        env:
          TZ: America/Vancouver
          NODE_ENV: production
          PORT: '3000'
          PUID: '1026'
          PGID: '100'
          LOG_LEVEL: debug
          NODE_MAX_OLD_SPACE_SIZE: auto
          DATABASE_URL:
            valueFrom:
              secretKeyRef:
                name: bookorbit-db-bookorbit
                key: POSTGRES_URL
          POSTGRES_HOST:
            valueFrom:
              secretKeyRef:
                name: bookorbit-db-bookorbit
                key: HOST
          POSTGRES_PORT: '5432'
          POSTGRES_USER:
            valueFrom:
              secretKeyRef:
                name: bookorbit-db-bookorbit
                key: LOGIN
          POSTGRES_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: bookorbit-db-bookorbit
                key: PASSWORD
          POSTGRES_DB: bookorbit
        envFrom:
          - secretRef:
              name: bookorbit
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /api/v1/health
                port: 3000
              initialDelaySeconds: 20
              periodSeconds: 30
              timeoutSeconds: 5
              failureThreshold: 3
          readiness: *probes
          startup:
            enabled: false
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: [ALL]
            add: [CHOWN, DAC_OVERRIDE, FOWNER, SETGID, SETUID]
        resources:
          limits:
            memory: 2Gi
          requests:
            cpu: 50m
            memory: 256Mi
    pod:
      securityContext:
        runAsUser: 1026
        runAsGroup: 100
        runAsNonRoot: true
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch
service:
  main:
    controller: main
    ports:
      http:
        port: 3000
route:
  main:
    enabled: true
    parentRefs:
      - name: http-gateway
        namespace: envoy-gateway
        sectionName: https
    hostnames: [books.g4v.dev]
    rules:
      - matches:
          - path:
              type: PathPrefix
              value: /
        backendRefs:
          - identifier: main
            port: http
persistence:
  data:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 5Gi
    globalMounts:
      - path: /data
  tmp:
    type: emptyDir
    globalMounts:
      - path: /tmp
  books:
    type: nfs
    server: 172.16.10.10
    path: /volume1/Comics/Books
    globalMounts:
      - path: /content/books
  comics:
    type: nfs
    server: 172.16.10.10
    path: /volume1/Comics/Comics
    globalMounts:
      - path: /content/comics
  manga:
    type: nfs
    server: 172.16.10.10
    path: /volume1/Comics/Manga
    globalMounts:
      - path: /content/manga
  webtoons:
    type: nfs
    server: 172.16.10.10
    path: /volume1/Comics/Webtoons
    globalMounts:
      - path: /content/webtoons
  webcomics:
    type: nfs
    server: 172.16.10.10
    path: /volume1/Comics/Webcomics
    globalMounts:
      - path: /content/webcomics
  rpgs:
    type: nfs
    server: 172.16.10.10
    path: /volume1/RPGs
    globalMounts:
      - path: /content/rpgs
  stashcontent:
    type: nfs
    server: 172.16.10.10
    path: /volume1/StashContent
    globalMounts:
      - path: /content/stash
