---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/library/common/values.schema.json
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 5984
    runAsGroup: 5984
    fsGroup: 5984
    fsGroupChangePolicy: OnRootMismatch
    seccompProfile:
      type: RuntimeDefault

controllers:
  main:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      main:
        image:
          repository: couchdb
          tag: 3.5.1
        env:
          TZ: America/Vancouver
        envFrom:
          - secretRef:
              name: obsidian-livesync
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /_up
                port: 5984
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
          startup:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /_up
                port: 5984
              failureThreshold: 30
              periodSeconds: 10
        resources:
          requests:
            cpu: 10m
            memory: 128Mi
          limits:
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
              - ALL

service:
  main:
    controller: main
    ports:
      http:
        port: 5984

route:
  main:
    enabled: true
    parentRefs:
      - name: http-gateway
        namespace: envoy-gateway
        sectionName: https
    hostnames:
      - "obsidian-livesync.g4v.dev"
    rules:
      - matches:
          - path:
              type: PathPrefix
              value: /
        backendRefs:
          - identifier: main
            port: http

ingress:
  main:
    enabled: true
    className: tailscale
    hosts:
      - host: obsidian-livesync
        paths:
          - path: /
            service:
              identifier: main
              port: http
    tls:
      - hosts:
        - obsidian-livesync

persistence:
  data:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 5Gi
    globalMounts:
      - path: /opt/couchdb/data
  config:
    type: configMap
    name: obsidian-livesync-config
    globalMounts:
      - path: /opt/couchdb/etc/local.ini
        subPath: local.ini
        readOnly: true
