# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/library/common/values.schema.json
controllers:
  main:
    type: daemonset
    pod:
      hostNetwork: true
    containers:
      lms:
        image:
          repository: flungo/avahi
          tag: latest@sha256:45112a3642d4c10ad62219ec6c5391578bb106b201a44872fe680128d1366ae1
        env:
          REFLECTOR_ENABLE_REFLECTOR: yes
        securityContext:
          privileged: true
        resources:
          requests:
            memory: 250Mi
            cpu: 15m
