---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/library/common/values.schema.json
controllers:
  main:
    type: daemonset
    pod:
      hostNetwork: true
    containers:
      lms:
        image:
          repository: flungo/avahi
          tag: latest@sha256:0a9981953ecffdad38b29663e424b25ba6e7cafaf6c238b0e1a2dbf04e4e7089
        env:
          REFLECTOR_ENABLE_REFLECTOR: true
        securityContext:
          privileged: true
        resources:
          requests:
            memory: 250Mi
            cpu: 15m
