# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/library/common/values.schema.json
controllers:
  main:
    type: daemonset
    pod:
      hostNetwork: true
    containers:
      lms:
        image:
          repository: flungo/avahi
          tag: latest@sha256:4154ff60b76c6925a9cbd4e24a6910122d5e1decc8a4504bf9fd3f92621e5e8d
        env:
          REFLECTOR_ENABLE_REFLECTOR: yes
        securityContext:
          privileged: true
        resources:
          requests:
            memory: 250Mi
            cpu: 15m
