---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: default-logging
spec:
  fluentd: {}
  fluentbit: {}
  controlNamespace: logging-operator
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: os-output
spec:
  opensearch:
    host: db-os-tor1-85523-do-user-8094590-0.e.db.ondigitalocean.com
    port: 25060
    scheme: https
    log_os_400_reason: true
    with_transporter_log: true
    logstash_format: true
    logstash_prefix: kubernetes
    buffer:
      timekey: 1m
      timekey_wait: 30s
      timekey_use_utc: true
    user: doadmin
    password:
      valueFrom:
        secretKeyRef:
          name: opensearch
          key: password
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: all-to-opensearch
  namespace: logging
spec:
  filters:
    - dedot:
        de_dot_separator: "-"
        de_dot_nested: true
    - parser:
        key_name: message
        parse:
          type: json
        remove_key_name_field: true
        reserve_data: true
        emit_invalid_record_to_error: false
  match:
    # should be select or exclude, empty select is everything
    # container_names
    # hosts
    # labels
    # namespace_labels
    # namespaces
    # namespaces_regex
    - select: {}
  globalOutputRefs:
    - os-output
