# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/library/common/values.schema.json
controllers:
  main:
    replicas: 1
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      main:
        image:
          repository: ghcr.io/cenodude/crosswatch-dev
          tag: dev-a1c191f
        env:
          TZ: America/Vancouver
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthz
                port: 8787
              initialDelaySeconds: 30
              periodSeconds: 10
              timeoutSeconds: 5
              failureThreshold: 3
          readiness: *probes
          startup:
            enabled: true
            spec:
              httpGet:
                path: /healthz
                port: 8787
              failureThreshold: 30
              periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
          limits:
            memory: 512Mi
    pod:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
service:
  main:
    controller: main
    ports:
      http:
        port: 8787
route:
  main:
    enabled: true
    parentRefs:
      - name: http-gateway
        namespace: envoy-gateway
        sectionName: https
    hostnames:
      - "crosswatch.g4v.dev"
    rules:
      - matches:
        - path:
            type: PathPrefix
            value: /
        backendRefs:
          - identifier: main
            port: http
persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 1Gi
