# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/library/common/values.schema.json
controllers:
  main:
    replicas: 1
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      main:
        image:
          repository: ghcr.io/usetrmnl/terminus
          tag: 0.50.0
        env:
          TZ: America/Vancouver
          API_URI: https://terminus-h.g4v.dev
          HANAMI_PORT: 2300
          APP_SETUP: "true"
          KEYVALUE_URL: "redis://valkey:6379/0"
          LOG_LEVEL: debug
          DATABASE_URL:
            valueFrom:
              secretKeyRef:
                name: "terminus-db-secret-terminus"
                key: POSTGRES_URL
        envFrom:
          - secretRef:
              name: "terminus"
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /up
                port: 2300
              initialDelaySeconds: 30
              periodSeconds: 10
              timeoutSeconds: 5
              failureThreshold: 3
          readiness: *probes
          startup:
            enabled: true
            spec:
              httpGet:
                path: /up
                port: 2300
              failureThreshold: 30
              periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
          limits:
            memory: 512Mi
    pod:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
service:
  main:
    controller: main
    ports:
      http:
        port: 2300
route:
  main:
    enabled: true
    parentRefs:
      - name: http-gateway
        namespace: envoy-gateway
        sectionName: https
    hostnames:
      - "terminus-h.g4v.dev"
    rules:
      - matches:
        - path:
            type: PathPrefix
            value: /
        backendRefs:
          - identifier: main
            port: http
persistence:
  uploads:
    enabled: true
    type: persistentVolumeClaim
    storageClass: longhorn
    accessMode: ReadWriteMany
    size: 10Gi
    globalMounts:
      - path: /app/public/uploads
