apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: changedetection-oidc
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: changedetection
  oidc:
    provider:
      issuer: "https://auth.g4v.dev/application/o/changedetection/"
    clientID: "jkjD5CplbUP0KqwpeBY2rt1x1CXUbzlHbtq0jNsu"
    clientSecret:
      name: "changedetection-client-secret"
    redirectURL: "https://changedetection.g4v.dev/oauth2/callback"
    logoutPath: "/myapp/logout"
