---
apiVersion: gateway.networking.k8s.io/v1
kind: ReferenceGrant
metadata:
  name: stirling-pdf
  namespace: authentik
spec:
  from:
  - group: gateway.envoyproxy.io/v1alpha1
    kind: SecurityPolicy
    namespace: stirling-pdf
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: stirling-pdf
  to:
  - group: ""
    kind: Service
