---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ext-mysql-operator

resources:
  - https://github.com/halkeye/mysql-operator//deploy/
  - ./mysql.yaml
  - ./secret.enc.yaml

images:
  - name: ghcr.io/halkeye/mysql-operator
    newTag: "v0.0.4"
