---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ext-mysql-operator

resources:
  # crds first
  - ./crds.yaml
  # after crds
  - ./upstream/ns.yaml
  - ./upstream/operator.yaml
  - ./upstream/role.yaml
  - ./upstream/role_binding.yaml
  - ./upstream/service_account.yaml
  - ./secret.enc.yaml
