---
apiVersion: mysql.operator.luktom.net/v1
kind: MysqlCluster
metadata:
  name: mysqlcluster
spec:
  host: mysql.test.luktom.net
  username: doadmin
  secretRef:
    name: mysqlcluster
    namespace: ext-mysql-operator
---
