---
apiVersion: mysql.operator.luktom.net/v1
kind: MysqlCluster
metadata:
  name: mysqlcluster
spec:
  host: db-mysql-sfo2-06502-do-user-8094590-0.b.db.ondigitalocean.com
  port: 25060
  username: doadmin
  secretRef:
    name: mysqlcluster
    namespace: ext-mysql-operator
---
