# Network-specific config options
network:
    # Displayname template for LinkedIn users.
    # .FirstName is replaced with the first name
    # .LastName is replaced with the last name
    # .Organization is replaced with the organization name
    displayname_template: "{{ with .Organization }}{{ . }}{{ else }}{{ .FirstName }} {{ .LastName }}{{ end }} (LinkedIn)"
    proxy: socks5://home-socks-proxy.tailscale.svc.cluster.local.:1080
    proxy_media: true

bridge:
    permissions:
      "*": relay
      "g4v.dev": user
      "@halkeye:g4v.dev": admin

# Config for the bridge's database.
database:
    type: postgres
    uri: "$MAUTRIX_DB_URI"

# Homeserver details.
homeserver:
    address: "http://matrix-stack-synapse-main.matrix.svc.cluster.local.:8008"
    domain: g4v.dev
    async_media: true

# Application service host/registration related details.
# Changing these values requires regeneration of the registration (except when noted otherwise)
appservice:
    address: "http://mautrix-linkedin.matrix.svc.cluster.local.:29341"
    public_address: https://mautrix-bridges.g4v.dev/linkedin
    hostname: 0.0.0.0
    port: 29341
    id: linkedin2026
    bot:
        username: linkedinbot2026

# Settings for provisioning API
# provisioning:
#     shared_secret: "$PROVISIONING_SHARED_SECRET"

# double_puppet:
#     secrets:
#         g4v.dev: "$LOGIN_SHARED_SECRET"

encryption:
    allow: false
    # pickle_key: "$ENCRYPTION_PICKLE_KEY"

# Prefix for environment variables. All variables with this prefix must map to valid config fields.
# Nesting in variable names is represented with a dot (.).
# If there are no dots in the name, two underscores (__) are replaced with a dot.
#
# e.g. if the prefix is set to `BRIDGE_`, then `BRIDGE_APPSERVICE__AS_TOKEN` will set appservice.as_token.
# `BRIDGE_appservice.as_token` would work as well, but can't be set in a shell as easily.
#
# If this is null, reading config fields from environment will be disabled.
env_config_prefix: BRIDGE_

# Logging config. See https://github.com/tulir/zeroconfig for details.
logging:
    min_level: debug
    writers:
        - type: stdout
          format: pretty-colored
