apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: mautrix-linkedin-sopssecret
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:1DYD/acEpRoUc3Y2C4e3gTJqsubHXn8=,iv:uclbAQnnzSaSE/dFU8rdqggJYkS8NrIsxGrCe878i3M=,tag:BSKzAJ5Ok3Sp8JOsSXO2rQ==,type:str]
          stringData:
            BRIDGE_ENCRYPTION__PICKLE_KEY: ENC[AES256_GCM,data:Zgj5vHu8InB3GkE5BoZJA5k3KId5Y/+1m7m2FDMjP/UFfQ7yEAwTP6O9zdXgiFq92navcJ2LteL4BKYspzZn6w==,iv:zxh306HoZrZ9GZjDK+CrdPrAfBsLaaeI7GmmEmDLjhM=,tag:BupAXpZycgiCDYOph04eVA==,type:str]
            BRIDGE_PROVISIONING__SHARED_SECRET: ENC[AES256_GCM,data:z8GQrJ7uS/5vDYMGEb5uMe2sTsSIiLi//G5LSprpfIWGaX7OYuSqJdLfpKBSAoxXj1Mq3PZ1MuPJcJtcvVX8h2JqXZOJjJLC7wzspFAwTz40SAh5IFgxEHxSIupBv7+BARGXEGONYvqY5nSYRXFeDi7YsiHJ6brkVUsxRw164HI=,iv:zK7zZHewa7LuUm90hpgG06yioeWs7cXFMuTIjs6B4TY=,tag:+dU7f6sR/FhGn25oS5orCw==,type:str]
            BRIDGE_double_puppet.secrets.g4v.dev: ENC[AES256_GCM,data:jI5mNRt1YHIrpORkUK6QqC7gvX/g5agbRQ3gfI9HZV3JzIVi2Zy7N7PsxC2QnSdc5uk780eqV03991yeeUJlpNpxPjHbamee5w==,iv:OgrK9YFXABq3QeIl4/CG2BqKLF34vujRnl9WMJeACcQ=,tag:fuuPSoFUOslBQRyLvs95GQ==,type:str]
            BRIDGE_APPSERVICE__AS_TOKEN: ENC[AES256_GCM,data:3UkA8E0akkLPZMde6eqbvcWc3fjoQaSNh2zgNJZ3eku3NG8r+/re4bfr1F7Dv76QRcMppEjC1e+Zbhgpo3eBAg==,iv:EIR4pgGidQBsEHWzlBlvak51KhMX8dGysZQNyd+3s68=,tag:nROZxAA5EgPRYfwmz3uNJw==,type:str]
            BRIDGE_APPSERVICE__HS_TOKEN: ENC[AES256_GCM,data:ubVMa1UO08Tog9Oj+8RTmrQBnYggCFUyoXj9A8KyR0fjBwvz4e+Y4vBWKWm3rTHZqR9e5cAtPVpw+6QucraOJQ==,iv:wacFXsgCNm9UHEPOvoChZtqW7IqWj04TJCZjbbDgVWY=,tag:sCRpCnqDK6dX0ujLbKcCjw==,type:str]
            PUBLIC_MEDIA_SIGNING_KEY: ENC[AES256_GCM,data:ZftyAg6lKEP5llZynKrOVJ/0FWtKLk69mKPZMIqyKq0NRXLHhdDMVBBFMp/Q9wXF8AqYbLOZ1qgDEg8BRpMHaA==,iv:KCy0BVh0PZQFt4EM5LPTPnHPpOaO7raEV9HxfDw1Gck=,tag:P9kUJUTPfPB6LRvdN/6Jkw==,type:str]
sops:
    age:
        - recipient: age1vqm5gwkmf38jsmt3j4lm3fdslausskaadtz360ewn0g7z2fchahqyr694v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOekZDaHoyZVV4WmJDVEFB
            bzZNbDZkeDJVV2pFWkppWGd0QU1XVmVIVm1ZCjZiZmNUTnFDeEI5ZzlpMmFaRGZU
            bWxKRVgxZE9pbUdoemM1VVd0Y0NBTkkKLS0tIG1Vd1VaMVgwaGZVKy9HMXZmNGdH
            VTdmZ3p4ZEN5R1BFVUxNdjUyV2F2emsKmrIe/w/meq050UARkrTF2RxJdC5D7Owa
            1+nPf2DThgDorPnnwxDeZ8LE32ceRhuh053+17+DZn571MW5gYUuvQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1aqel4n2xyfjmzjgey0mhxzhlmg2qd7xusjweku4w8u94dsq2gpmqye3wus
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ZDhDZGd2N2ZqbGNYU1ZM
            clJJY2hzL0w2anpJTmJaK0lQSjRDT3c3S0NZClNXODRLWHF2NlZxa29oZ2xvTzc2
            a0RZZ3g3dDlFUkkxYWZWdkVjTm42akkKLS0tIFpUWkZvL3J2ZjRXdVZZMFB2Rkdp
            VEN2d0lsQmNYeGNrZklGVHNuTGRPWkUKRkk2TJGhXdZ1ShyWqjSgOD4TswFQri2Q
            +N036LmuVWaCstoZg/2lUI9tyj4Yebw6ANeGgddRNkgu1mJBqZT0LA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y562y0u4k8y0eyq56s4g00ssd2cduamddcgfpu8fs7t00pfjss2s9nymt8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEM25PYUNacndSRXBLclhM
            ZEM4NHVwZVJTUnJhSzJMRSsvMHVvLzNFaWlZCnF3MlY5WHVhaHlKZml4OTdBMkho
            NHlpNVVFdnBYZVE1MUtkVy95UzZTZ0kKLS0tIDlvYnlNLzdhanU2TzdvUk11cFo3
            bXFzd2g4YS90NmlwKzcyQ3dwc0J4ZzAKRsre2BIsBEf5Cu5x9viVWn3okWTKZ9VQ
            W/cuz1Xi5y93URJttWJTth0lhapxMSsI4FaO9VYoVZpB16qN3gmQZQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lv53trxftjem0a4hewf9h9dmp65cql6ycaj5q8kvfnfspccg747s6lxpxg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXY09uM05VWmhJZjZWb1ZQ
            UXl3Yk1hZm16S2NhZFFxaVBZazRyRmZhOWhJCmpoL09ZYjRoVm9NSmx2UHAvaW5q
            M0lDbGtxSDUxdmZ4MmNGK1VWeW5EVjQKLS0tIG1DZW1aYTJrNEU1SGpidU5STmpn
            elRhcUQxK2F3SkNBYktWQ0hmYTd6cmMKW9m4vpqjCr5OoBHlDmezixIqOn6wlfjx
            MwGB1VN1/j3ufx8YWRwmUAoAXGnwUPwQRjdAZVjnDLpTeWBt25gQlA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ryqtmnakl6rc3z6qpqkhmw5pnsnzy2arwv7ecnh3ayf0za5pgtqft7lcn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUG9DUmJyUVFIdi9KMHZO
            R0NSb1ZESXVxV0hqcFBCVWtkckFOVnNBN1FrCjVBSSs2dGp5U21UWGVpKzNtYytn
            ZjcrcGxvTS9JN25tdjl5RDdRdGtTREkKLS0tIEtOOVpIU2RBKzgyMkhYVEFVMk5S
            ay9PNCt6OFowL091aDZaYmlBTzRGUUEKLku29kxyJ4eOnSvcWm3o5yPP3affZd3l
            XasVujTknUK5bXGHBDwtvd2yqPjU/MA7iGmUQSv0t1Z5P/J+TawEfw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFB0EXmaOVc61axVxDoWw1Y7JypG4LFFbS6+96dFY2VS
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGt0aTNnZyBTbG9Z
            TEE1QkhSbldKRDZJeVhrTzNwR2ZMenNQb0U0UVhTVHBoTm5tRldRCk9qSWZ5RElC
            OWJ3bkdWbnc1MlRYaDBuTHVWU2tvWSs3aTBvZ3F6SklIOTQKLS0tIGJsSUIwc0Y3
            cXFON3ZCcmYzUnQ0V2RaeUVTckxSUWZ6dnI3MDZXWUlsaVUK4SrHdXH3ox5bzIHK
            lOyqS5rFgkIR2Zl5JPK+LycvA8V+w9skyduPxmLrFsqD/gQG13OaR1hFORQcL92z
            6LTIeg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age179mmzgpy7ldyh3w6zld9vxjegxv80mkt6kffgg5enyquqrwnspkqv7sq7v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRmZqbzBvczRnQUFoc3ZV
            U1dCdUlBb05XRktvUmxTOGJGY2Zxd3ZyR1FFCkJzWlU0ZEx1RVVWYlI3YlBsQjV1
            THlQbGZKVzM5VjdCZmplWllHemJqUWMKLS0tIEZHR2pNT1FmcENwL1lqRTZOSnZS
            TzN0WGlGajR3eWthLzFkbVpmUnhNNk0K2FqZ6alD1zuyW+Ko5hRkM+DNuLj+lO5/
            t3M/WQPNGULThzp7xkhU8KacC2aeVYPO7p3hIaVGdyqFw1kQtWEtSA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k63d5ts2w8hfvdar7lan2qamhcgrjpfdv4um97q0ehjs553x4sysx08xcg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByYzdTYUNvbkd0WGVXamp3
            VUV3UVNXam9GTU9hbysvc2ZkOWVZSFRGMDJjClJrc0N6ODRzcEJzOU9FMmR0U1hD
            SjZRYkNXVDh3Z1hsVjdCZXVobEJobFUKLS0tIGhTS05iM05YWlpSenF1cEgrZnlr
            T1dZZ0NHM1RoZk1ORjJxVU5ZNERsZ2MKIZnl0MWdch45naGvfSxmbi2FD5NGJqHm
            Jfi8wd7ivmiWirjJ9Ne7RPuvzLlzQToY/w+uZooIsnPO37+WJl8KAg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mkkltp58ptsvn5t7x8anr4hy20z0z6568nsljfa7tmwx07ug09aqf6rxe6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbS8yaFJnRTNQSUVnNmJG
            Vm82TjVUTVdpdWoxMjNWVlN4bXFNb2tqZXhFCkNDMiszMjE3MnhobFVpb2IyQUNv
            TXMwWmU4TFo1dDhWMnJIYTE2TjZVVmsKLS0tIHFka2U4ejNHWi9LUm4rOGx3bEI5
            RmtvZEVoUzMzWnUwK0dxUmQ0S2N5Q0UKMxzZban2DaEdbr01q1IhsFwJFegRqpjV
            OwT2yFAjQUhAqbP2QQoUT7130SQ5D1WnG0AAO1ojMPboBem0NUZhpQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tfj0kfd2twsa655d5hx2afczlpcfzw7hapc07gr7ywnqq08qxdtsud2gfz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZTUwMStZYWtVdENYMkFl
            b2Z0YUk3aEtzMmlhNzdVQmFOTnBGOVJHaVFNClIxc0c0YXdSRXd3eXRLZE9zczlK
            YmorOGdKeDlPck9sb0hFdGFTeG1pNzQKLS0tIDdQOWNOTXR3TjlQKysvNzlDTUZx
            d2ZkcUdxZ2NqVGY5QWxTaVpWd0VuZ2sKRqwKo0YrBtzP3o7twRo0O2q09kVgRp2a
            fARELVvB6YIiMFMeMSE1fHyEBYCeR6GH3tMTDXz0jLgVRvyG57OX/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-21T05:40:36Z"
    mac: ENC[AES256_GCM,data:chwAoqSM89mNN1AVxkPoHUSpTlZNA4WWtUv3zLT7JZMMx3r2agyECF6zyia0AZT0Oo8D59I3vbse/kAxgZDtt1WgH4TF6rm6Et/hfNszeVp7Aovlx4uGMk+sV6dS+B2XD1SgvF6ksPZ+Nv53RvpT1k1vVr7KCEk1U71+1fmnbsQ=,iv:u6iQLJoGkyZfZwlPFTApEsl6BWP9wZZ8E/nYcFlEoAk=,tag:c7ROeYz2uIP5wSpyOrpnpQ==,type:str]
    encrypted_suffix: Templates
    version: 3.13.1
