apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: actions-runner-controller
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:LPJUSHobNUqRuGvGnlWFwi9RHNT1N3nWog==,iv:Aj30IUr5S08SQ0WSS+CDc5A7DiCSQaTdASUsCchj688=,tag:VG3hOHk5R2hCQ3Sa/qVwSA==,type:str]
          stringData:
            github_app_id: ENC[AES256_GCM,data:xrXbm0G6xw==,iv:nnrwyq1CobJLhiSatHlC3LASvuFKyaGG8XvYBtFqpuc=,tag:gASS45hZEVCnehYfQhuDCg==,type:str]
            github_app_installation_id: ENC[AES256_GCM,data:uF19TQMPNqjH83wes9xJdWM5Svc=,iv:Xg17fIoLE1hbVGcZD17mqhvxscWy6CyK5ni+qgdvh3o=,tag:vbmGKgNVdLNiLWjExZOLDw==,type:str]
            github_app_private_key: ENC[AES256_GCM,data:yRo7q6rdjfLYtuRJM8i0M3AwwHOLTHbmWx9Pk5Gw+4iSPaH5Ry8CnelgS73s5FVlQeYrNeAyKfOE2+jayxioc18fZLe7KKYwsTGKMb3WY6LcUPB4c0eMCbnd3NCNzxQl4r9WlewQPHyF1QQ6XVaD01zEvoA3vyF+jkCKZrlOZTHDjxE6D0RS0WiWlL6oGN3buoKo9a7yhD8o9SgmLkciX3TmO4guBL8BAi7mci16O94kRrGqZvxxhP0SHjd5+PcNLl/vNpiBxR3AItslkPRc/htFbxdfXL17ScUKAzLSbFS/s9zGgw0Wve7rKi55S+lsh7rFO1hZOmRG5hLSWrcDtyyxgNXrCInqtbNAP6JB+EljicoQdsFycKyA/8EGqI4t3vWgMDmc8YpgcfnvJjiVJaVNRfYD1f1cwzLqBeQFVXqCwdEuGc/s2a8Tx8M1W40/P7fXm0gFtBnG3LMgXS0M6yfhds1jObHrC64s+uKhIGhax5kifsYCE9C5THj8t52IlF3619SpqanpYlnKTzQNgdu0FgnmzGC0zBBBfWCBebtu02pk2pT/aVDK93m5YguUwEzQ4JL3XZoC/OdrvxVcOUnutlFXYBqG/yoLtLKTdYtZByACu7FbVeEvE5r7K7dybzKBNk7GoFRS3FpncZyQiLJhjrkF3KxlNPg46viW0+S6HSKEb7QbIMkAd93z7nOWfXHNwEyb+oLxXRsn9l+zHpfzCGZROVpnPUuY+3o6E+r9nwLNIhmlUP73GxoLKjIUrhKBzrhAL1WxdTsSs825xvgtvc6BjjneWuhT4RMxvWbkrGVRRI3Yy82Mcw1L+LQXYoncu5j0/cnRTBpij5w8I9bfXgFQhQhhInUkk2rbdhPBk09z9V9lvM4QCoPqoH/QshauIJH7Z5T7gVyKczVos7GkkpA9Ws1SZLbJLtKnn5rvEqZFDabRmw4MA9CqYykH7j0aUy4b6Srj7gTnooXa+95iDaUe/vPkoSZnpXhKPUFHcnmcjDHMJyJNlj9TBFaOmaZGxxFBwFuPETubsiYZIOmUXV+ubvXelLv+9IQIxmhctZaonLhGxKuOJ6wbcoeb/XCNrMegaanvISlZgCeHBQ0dgrkVQgQKipQPgT2aBzSJjZ8ewa7bB6CsgqhdmRvLPxqT9XXm4ntHJ89kFRXO7Ya69JGEfWPVex6ZrAlX3ugnlUP3cjFGtbtcV4LKUHfi6+BhkkY4OeIOHPfUEb2LbP6XPykSgGhcgdKwX641ZLD+XW1ApkHe7VyKWwgMc1fXlgHaQjJbRJW+JkhLvSiwjibldqLogeGL9Ko4rYGLj800Hb5/IDs3vHKhHce/HyisoZe+it4OqnpSO48t5Bx9dd8bAJgs6UUMtUsza5knJBeFDH6P75iP8Qx1p6NlP6OivE3gE2HAWLBxKf4lCnKfvRwTEloH4I6cu+9rk0nBq4zVZGFHGKllGNdoRb3QWEJqkkSe2QBxdY7c2Qyt+H/xQ6iUYe/Z1dRTCH/G1EqNgmKjP9qQT8fqqhb/w7WmDx1Fsf5GQjpaQs8Vryxfv2w3AMt5QLcTh/l05e/mYk/r0sZ+3lGwevS5VRgEOnMgCqGGHhS8k7+R7wVtWlu79xejY9+XgCWU7GWuljZc5bwnKNamcf+OvBDrftIa1zqGbCN4GtBkrDUcIKFhv2MZ1/M5kG35SrNJ7Zc/NFEt9cYFBBeW+YAlE4C2Sx5I+p8Dkh65TH6bCluhUaxm0Hbn/PILWTlKFMYIAZ+cQ5erPhe3FnR2oyoAXxBFb8y3lIkwYOv5CZtNWcWLfUcwygyg4odnSYGnJ8lM7l74LUwx1861omgB01lS0BfpByhqCJFIodxVKJe7hozVVF/vYNy9ogEQHgfV/WnrABcHfRT0v28Nqfqeens10RHeMo37YxNdEVRvhwdZRItyniqZKdQIL/PrIp8XFfbO/VaW4iu51tKCWrH8Y8AqvnvgoVy7kY3+v9+BVqktWQ+kJDHmg4jexW/nH1iZS/gLwTzK7k6uhK/7CC+6/5RbBzdagp/pjrpXT/YslHD7rTvKEiX9pBkR7JP5eq1OOd5rj16C1KPy8ovxoUu30WvJyTQ5nw5pXOa1ZHFP37QYl15M23dmh1puPhO8AaX0NFr1S9gxTuR5zOM+nXIWa+mcbdCi73sdGCS90xRZZBNE+yN3IM9Np5NE0ajo7EPvvqc8dI94lVfAbNiOh81F1TgHKkFTMTI3LQ==,iv:bYuF9C9AtMHM0JmGzc57eMDSMJo2tP6IVXOcpPU/jBg=,tag:fP3Q67EOrYQJMnPKlW7unQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicEw0TlF4ekZvYy9ncnJu
            ZkZIV2lLSk92Y09oRVNPU3pMZC9nMzFyekNNCnBnRVZBT2cxcXREVGdHMmRrdFJ1
            UDhPL0VlaXVOTEpuTTVGLzErNWRGOFEKLS0tIHByUEZTbUJNcnA2amltck1zWWp4
            M01Cbkg3SnF0OTVZWG9QS1c3bENNRDQKq9ThB0G9dZOHiyJHZPvy6P41qDpa5xNe
            oW7tRVyoxjlJqsJtg4vVeKsnQQEfQZ1zN/J0jrs1cjqzxLPMYKDi0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vqm5gwkmf38jsmt3j4lm3fdslausskaadtz360ewn0g7z2fchahqyr694v
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqd21yL1NsZVZyVlkweTJM
            aE5wOGNvWTNJMWdYaTJYNnRmQi9WTXBEbW5vCkJrNHhzVTJMbnVEUlU2MVRYbVgz
            WlBFRkNwa3pDQVRsbWRWODF1VUtVem8KLS0tIFQvaDZBYy9kczh0MllOMi94YWZP
            MHI2WkFNMEYzWHRSa0xFeTBPNHlIL0UKGw8Q/ebh38HNkglyKKVFVzfSbZvvM/UC
            Fsox9urJaj3mWoFRgW8hy1MtNpNgYSAD09w6I2mbrDS+Xpp0FHgX5Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1aqel4n2xyfjmzjgey0mhxzhlmg2qd7xusjweku4w8u94dsq2gpmqye3wus
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMV096QVdVNGtlazNiQjlq
            VEIrUE9TVEdRZ0pVUURmZ2phSXFxcldNblJvCkUzQkxMRnBkRUo3N0pKVzhSRmY3
            RGF5NjlBaG4vWkxIRHZtVlVOWXNQU2sKLS0tIGVUak9RWEFuSXVabkhxb0h5MWNq
            L0MrNjA1NlFWQW1KQ0Fuek10VC84bncKAXctf7jFJ7RkpzDadG20QLv7GrZaQZva
            6gXSlT05EUm/kGYKErpnegOlLHH7GvuE/vVn1SCV9hfqdUfhY7MG1g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y562y0u4k8y0eyq56s4g00ssd2cduamddcgfpu8fs7t00pfjss2s9nymt8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwYjJJVFNSZDJjZ2FyZitW
            eXNicHMzYTIzK1lvQnNTVGV0dXNraEtkdFFJCjZqY3VCQ1FTMGYzZmxObStDblZD
            OCtIdHBZOFNUbHp0TFBzMkNpSG85M3MKLS0tIHVrSFdLN2Z0b3duTENxZXVQZzBL
            c0NrbEQ4RjJ3SzRXZ1ZEUzRkeWluQnMKAyc6HwOELfkhD6hJY63GAMjR+gIpJ5b8
            UJ6HL0bwZBqPPTsdCYVgFLs1CsilSrZirzKrsFmyyn7MryPMLqA+Wg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lv53trxftjem0a4hewf9h9dmp65cql6ycaj5q8kvfnfspccg747s6lxpxg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjT3EvZE9lcmZEa1JVZ3BV
            TzkxL05zbzFsc1Azeld2YkdUR0lCcVJpeG1JCjVsUDdEaFREMGFpemFWd21EUzEy
            b1dPNlQwakVIWmNSNzJsblZsRExxNjAKLS0tIFdCR09xeVc5Uk1oVkY0MVIzZ3NP
            SkNNVUxkeldpTGVvbW1Hd0VVQWZXaU0K8cXD1oz8Nq++i2+TkksbplqRj1PHJYyu
            0Q55RQWQvhxLjgL4GGrM3zAYPT+7QQL2ZC8Ypou8Q837py9lQ8gUGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17ryqtmnakl6rc3z6qpqkhmw5pnsnzy2arwv7ecnh3ayf0za5pgtqft7lcn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGt0aTNnZyBGdVBY
            Y2pHTGRSYzdnUGpoMkVhTzl2Yzl5RU1uTE0xL3JBWno5VTVOT21ZClU2M3k2TVUy
            cUpSb2xHTUZ4Z3VJVUZtdys2bDhaaHR6TEJscHV3VFJDZkEKLS0tIDVaMFNBMm5p
            NktlVVZHRHh4Sml2UHA0N1Q4dEFzdEFsOUx4bUJFQWNxTDgKrHh4uyFfrL1pTDaA
            HwKkAIhAgEer7H6L/VEai+3/BjmZKGl56rPYapRPixiH6A50w6Ts7izpybKPvDMA
            4OUg4w==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFB0EXmaOVc61axVxDoWw1Y7JypG4LFFbS6+96dFY2VS
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAza2V5VDdMd3pxTy9mbG5Z
            eUFEUzMyS2RxSUsvWS9KWlNyS3BtdmR1YUMwCmRkN3N6OFZnZVczM216cTVBV1JZ
            MEx4YlM4TmpEV0lRdFNibWNvWkhpaDgKLS0tIG5Ddno5dzQvYkt2YVMwekdqbjVR
            V1RTa3VRSWJ2UkVnUnp0cGtVWW5zOXcK3tKnKg8+C2icoFNi16t5e9kV76jE14hu
            s3UwcHPbG3S2lQCbSfELV+fjU6M1PHj+X8+wTU8pqisMW91Cs1XQYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age179mmzgpy7ldyh3w6zld9vxjegxv80mkt6kffgg5enyquqrwnspkqv7sq7v
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUFRNMHRucVU3bnFBT2dy
            d1RJcEIrZzY2VldJZzlMcitodG5keThDdkNnClFsM0w5RFpYMmc4VTJHczc2ckpF
            eVdsdUFZUHpqbXhLWVpDNTZ2N2Era2sKLS0tIGZGcVlpZFh6d2ZjZzJXWG9kejVJ
            THlCM0wxRGYxak14TW9QTWswdFpEcmcK3mh/Q8vy7IgiQNqwyY0E5ALjha/2IzjF
            NKzMFMyADn7wOnV4WqwP7RIHZBD8AUEv1LbiresAoaF/nJZlSin6EQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k63d5ts2w8hfvdar7lan2qamhcgrjpfdv4um97q0ehjs553x4sysx08xcg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBia3lEM3VqWDdFYUVxRkhr
            YlpwSjdZMkNoK1JVRlAxcjAvSDVSSWJCb1dvCjMzYi81aWFnSVFwZCt2SFlCdXVQ
            SU5wZTJIYjNBMVhuN2kxdjlBZHBPQUUKLS0tIHZiV3VZT0s3ZW9UcUJuZU1hMHdx
            ZzhEOW52WmY1UzB0NHY0Y0dXTUYwVTQKNFNUJfDXB0WgF7kg0vtPPcqgDjyUmN9b
            44ZZxSzGjZN0We2l+IqOgQm7UhD0HcK+VjE64+hDX1M4u286OBzB7w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mkkltp58ptsvn5t7x8anr4hy20z0z6568nsljfa7tmwx07ug09aqf6rxe6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZlQ2bUxObStLSmNuNGh6
            bVpRYktMLzNEZWpkR3F1T25Wb0c3T05ZY0VFCnZOL3BCTGRZUHhQb1lKM0V5ZHhv
            dlZJZjJCQXpvT2FSQnNlL25xemNFODgKLS0tIEdqTVBTR2RML25GSFhHb3IzdStO
            MVlUUVhURDFhbitheGpCZUVZcGJkZWcKYx/TI/Pt4OH2t2b2v/M5SrZ21Gp1frDC
            OUCY/aT6GuGSE9RpDFLLLsBdSRQ39709aRL8bJYuXtGIBbh/Uuby4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tfj0kfd2twsa655d5hx2afczlpcfzw7hapc07gr7ywnqq08qxdtsud2gfz
    encrypted_suffix: Templates
    lastmodified: "2026-06-06T00:03:30Z"
    mac: ENC[AES256_GCM,data:2gE6Acf86xJ3NadXulj++SmX1aBbcreIkSvHH1ndAaIN5J8+b23W9hnfrHOlDv7CZ4l87ewav0CveCdSd3TP54U3T/yAiX7IqNFhI1XQmX06/Ej7wxYAtS9wcVSsbpbLKGS4LByMfNXGqd6ofuJmCYhBaAVHmwEUvPQFjI0kMUo=,iv:hDIJQrIr8dotKAjUq2G0gwO5o1BMXBW9ffB97iVM9YA=,tag:5gDV/T9b+XHyZI+B3QWDWw==,type:str]
    version: 3.13.1
