apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: speedtest-exporter
spec:
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/instance: speedtest-exporter
      app.kubernetes.io/name: speedtest-exporter
  endpoints:
  - interval: 60m
    path: /metrics
    port: http
    scheme: http
    scrapeTimeout: 1m
  relabelings:
    - replacement: "speedtest-exporter"
      action: replace
      targetLabel: job
    # - replacement: "<instance>"
    #   action: replace
    #   targetLabel: instance
    - action: labeldrop
      regex: pod
