apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: timescaledb
spec:
  instances: 2 # number of db instances
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    # Change the following to `ClusterImageCatalog` if needed
    kind: ClusterImageCatalog
    name: timescaledb
    major: 18
  primaryUpdateStrategy: unsupervised
  storage:
    size: 50Gi
    storageClass: longhorn
  enableSuperuserAccess: true
  superuserSecret:
    name: cloudnative-pg-auth-secrets
  monitoring:
    enablePodMonitor: true

  resources:
    requests:
      cpu: 500m
    limits:
      memory: 4Gi

  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required

  postgresql:
    shared_preload_libraries:
      - "timescaledb.so"
    parameters:
      max_connections: "300"
      shared_buffers: 512MB

  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    supplementalGroups: [101]
    fsGroupChangePolicy: "OnRootMismatch"

  backup:
    retentionPolicy: 14d
    barmanObjectStore:
      data:
        compression: bzip2
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: s3://timescaledb-backups/
      endpointURL: http://minio.minio.svc.cluster.local:9000
      serverName: timescaledb-001
      s3Credentials:
        accessKeyId:
          name: cloudnative-pg-secret
          key: S3_ACCESS_KEY
        secretAccessKey:
          name: cloudnative-pg-secret
          key: S3_SECRET_KEY
