apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: mautrix-bluesky-sopssecret
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:GuXrxHWShjMRtmHBa4BKj6q6GLRI3w==,iv:uR6hagK7zhly2Xy9W2Unqg08/CEniULfE8TQn8DyeGc=,tag:NsowbfVdFHEIge4FzoAcFA==,type:str]
          stringData:
            BRIDGE_ENCRYPTION__PICKLE_KEY: ENC[AES256_GCM,data:hg+ABmkyXYFgr1Wvvn9Qftyi4H/+tprT+AYQ9Eynnj2M+2rR0ZvPsEPQJ2OrqWnBjr5yg1Vv/yWmtHIV3E6VnQ==,iv:o1Gc2j1B2SQZ4K+PwYvKG90JKFzs7BEz1z0sTk2QzXY=,tag:68KOEzBQQJP2JPJv0aALrA==,type:str]
            BRIDGE_PROVISIONING__SHARED_SECRET: ENC[AES256_GCM,data:oyH03jN4JeFqM8NyIGf4kin6lMAAqeCCpxv50OIELvD0fdOmqyELLvPSvYtoZ/x0ywwWlWpN5tUwJpFlYf+xVA==,iv:oKF0nzYyaj4VCLpmVFSBnL3TwyNf/rXZ84+CVjEimgk=,tag:QYTVBzk8liKalwTVImF9hA==,type:str]
            BRIDGE_DOUBLE_PUPPET__SECRETS__G4V__DEV: ENC[AES256_GCM,data:wcD9GvJtjDjr0AqHrjKmr60cViFruFrCTxrkb1SnjSGodoRwmZYoh+Uq/OLASl9iOGrR1sWFUsvf3yrNEJqW6Dq716L7benRVg==,iv:uizl4aF6VYNn4zIf2bbAMdTGd0gk+A5lGiESpXyrKP0=,tag:4MTc6BAEebM2QJxwYP4Z5A==,type:str]
            BRIDGE_APPSERVICE__AS_TOKEN: ENC[AES256_GCM,data:o+IbOlfeHYMxrgTRpUW0mOsKA2G11VWLk6eehy37Di4V43qMuM2j9NRrb98rOg5tpRKR6tkyPffZ+UhXfj0mNw==,iv:g6pjIrO0tiCG0nB3jMsIQWuWweeE9L/H7+kqqIgiQBA=,tag:uVCP7uCZ+/hoMOWId4EAyA==,type:str]
            BRIDGE_APPSERVICE__HS_TOKEN: ENC[AES256_GCM,data:gYFntpBL7rD5GL87BoAR8AQdXmfIfHmikH8rfcMbvjXNDdmUZcV5qzCFHb65fEpvAaorHL2bWcfPzWwwUonQhQ==,iv:0wgAH+acc79XZyrNEfu3JDSSNUyHR/HJuXkafAMvYLw=,tag:aP5PE3f2wjCH8yQdKJ6GJw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSDY5QTNIZ0VNcEJWeHYv
            OXdiRXdQdWhySWs5WXJUL1lrQTY3ZW9xS3hNCk94NFpTOWJ1VWl4Z3F3eTZqZTVw
            TjhKRG5Wdk5DbzlPTmZZWGtCQ0llSkkKLS0tIGZzV1piVUVud0U2WUxSZHVwMHVO
            MURGQVVidXczOFNhODRvODB3WnBFZjAKPaGjwsLSW4ZOnzmV9r3bkpFDGSZH4W5M
            uLlZNpajjZmRNAoGJspE0pKHAFoRxXs8g1qQiAwNroCyNZXtNB6tXg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vqm5gwkmf38jsmt3j4lm3fdslausskaadtz360ewn0g7z2fchahqyr694v
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5TDdZQ0M4VmpSaTRuN3pT
            cnFBZGxzRVc5VU5lRFk3SWVlcXBkR3VuQWw4CnlZSUZzRGJBOWcwR3I4cVQrdCtW
            THp6VUllRTZjZWcySVZqZTNhcFhSajgKLS0tIFBzQ0E2NVdQZWEvamxIdFAyc2pI
            Z1hzV1NzcDYyWUgvQlhkcWcxeUU5U0UKheYBoNXsV1xTzb/6WUwOXPCEVyJgj9vR
            aTAvnUPHQICLZyCHwhOuQzRwBRDl/XB2HYT5AC+BG3HmbspSIX7dyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1aqel4n2xyfjmzjgey0mhxzhlmg2qd7xusjweku4w8u94dsq2gpmqye3wus
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4QzlxVTkva1QxRGd1M0lG
            QnVzaytxb1FoUW1XelpVeWxyYWV4cm9SNjNJCjFncXErbGZ4a1RxeFJMOUF4WTBj
            b1JnSHZxUEc2WFR2NThrWTVraEljUVUKLS0tIGQyTjNONVlFSm9QUUxOMGpaakpi
            UkRZU3BmM2NzOUtDQndBWjZLVkpDVkEKeSqxrwDKh53MlmomP+E0/j5IIYkx1saC
            ZUH7lE2pvMVXMZmP8M4hIR6rdTeKvLrjKdCHtXVStlUJLvi/70YG7A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y562y0u4k8y0eyq56s4g00ssd2cduamddcgfpu8fs7t00pfjss2s9nymt8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMGpYbEFlaHlzU21aVlZF
            YVNCV0FBVFJkWit2c0ZrbUMxSUVpVkc1RjNRClh4dUl3TmIrYkp4RUxqajhqTmVF
            UTEwOUhJRjgzMmlxdUdMN0oxK3J6NDQKLS0tIGZWNXc2d05NaWY1ZDQrU1VXdDhu
            WkdJVks3aEZxcEtwSGUrRVd1YjdGeTQK6/nCB26zX2PMiV+QiDpFoU3BOO7k/9Z7
            fUuX8lpyIsPvnhhxCDvbcvTm7QhSypa96r9f2joCYfMxELeHv8TD6g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lv53trxftjem0a4hewf9h9dmp65cql6ycaj5q8kvfnfspccg747s6lxpxg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJaE5TWDNvWDlmSStISkhJ
            K25tT0I5VzB0VzJ4Y0lsMmRjbGVxU3MxV1NrCnRiYmpmWUxBZDk5WEVXL2lyZ1Jy
            WHBKMnRnemVvc0RXSkdiZVprVEJVUGcKLS0tIE05Y25HZUFQKy9XaENhcUU0OFln
            UTR3d2pMdjFqWmRWeTFKRjZ2TGNmS28K2/Eu2YRK/Dgw/lbLLo97/rGcSHOm/ZAl
            L7uzx/Q6MNwemiXM57tNjLvq57zJVgJfDsVqGZ7ewLL+osRX8t+eaw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17ryqtmnakl6rc3z6qpqkhmw5pnsnzy2arwv7ecnh3ayf0za5pgtqft7lcn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGt0aTNnZyBZSTRu
            cUR6WXJNUjdYcUtVN1NqaHR3Slpta2QzOVB2QW5sTHIxYldpaFdBCnhpRnc1UEhO
            dXNPbmhFTTBrZVR6VHllempFYkdEVFJNRjlkbjRvQnZiSk0KLS0tIDNDeDdoamZS
            Ykh1Y1F2dERKbkRkcGYrYTZoM21meUxNeFd6N2tXZCtaY2cKi0n2obPhNk2dJHM/
            2eHXTsUvT1s+gPewtjQY9P0ysFyD3oBNWh4r/AkklzZGXf9yc5J6imBQuC88tg61
            xLYAKg==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFB0EXmaOVc61axVxDoWw1Y7JypG4LFFbS6+96dFY2VS
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Uk9XeUZvUkF3NHptdW1L
            b1E0TzhNaUNUNVBZKzQ2c2VTYXEyTHBOVGlzCnhsV1h2dmNzeDBjcm5ZRjhQWXcx
            L3MySXdYY3h4STdyNHBjUmxnYnVsS1UKLS0tIGFIMVp3Q3RxRGVPV015STVldXk5
            WlorUnI5Mi82K0tKcTNQVGVaQTVRV2cK7Q+AgMx/RPekjPjixyUI/X3Yys3DBxie
            gHhhVKEO5XFVT07sfjTyGan2t00VC3X15FsFVmYdVFt8MfQQNLxO1w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age179mmzgpy7ldyh3w6zld9vxjegxv80mkt6kffgg5enyquqrwnspkqv7sq7v
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzeFU2ZE1uZ0JYOGxMazRS
            ODM0UWdSNXAwZkthSTdWYStVZnE1eDZld0VZCkpJbERRU29lc25XbEhKSklKUFlZ
            dlZvTjNXalBjWGV1dFRsSGRJdWxoYlkKLS0tIFN6WTRWS1hhckFzeHJ3V2M3ODIw
            MEpGeVU3b24wQ2xiVm1BcnhWaTRWSG8KJzqVPS2+9z2RXeBEoKlEOAeAardbKveZ
            77At0XvopGJuDw0P3bARmNz2MkB0kJIejBZerGHBchu3pgUkG2/yHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k63d5ts2w8hfvdar7lan2qamhcgrjpfdv4um97q0ehjs553x4sysx08xcg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxM2NRcXVqbE4rd3hlU01m
            aXhDOGErQnpHU3RzTVkyWnNNUlJnVUJkeDE0ClVVQ3BEempEMjdJNDRMcFhDRjFS
            amJkN01Ca2gxckNNanh5L1BQcmVCNW8KLS0tIDF1bHlZT0VtKzNJT2k4YU50bWVR
            Zkl3aTdSbUZjV29kdWo5QkhDR00wNXMKgLrMng6Yu/9DXYxs2pKwDYT5ZW0WVMoc
            T0oiOq39aHNIQlBEle9PKa9XkoTyGyoyiILL5tkA9VJYeUTeZEzBcg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mkkltp58ptsvn5t7x8anr4hy20z0z6568nsljfa7tmwx07ug09aqf6rxe6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNE0zSjI3cldrY1ZsbEJC
            QkpQV2Q5Nlh2MXdtYkExRlZuVWRjWEl0VkVBCkhtZHc2bFJWcXpsb2lodktFZXhi
            Vi9EcGoyUTJ2U1BNd3BMb0UrQ212ejAKLS0tIDg1ZXdQbUVRREV2NnBzSW0wZ21S
            QVFsNUp0Q0xCOUxFL0xDc3J2c2lFeWsK1lqQpeHMYAJMW85dK82vkt/jUme9Mt73
            MIYGEDYILxnemgy/vDn+emWc14hot7tpRBX233GOXG5bbwVI72Szog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tfj0kfd2twsa655d5hx2afczlpcfzw7hapc07gr7ywnqq08qxdtsud2gfz
    encrypted_suffix: Templates
    lastmodified: "2026-07-12T22:18:57Z"
    mac: ENC[AES256_GCM,data:YS4YI5UImovceBQchmmFq6QM9JAlcKNBhrvLg5S0BonVAXmsBHKQDtSwmFMbJ66aMMXgrmi2zOEmjQFF5qe0661HBI1WFkZ1DWdzLy9hwx1mQA7I01A9XnX0hWDMTqMyCHcA+vZV57NCE75WySiMwTinCJqc/Dp728zHyYFcnK0=,iv:DwZ565/Jq0AuG8n9FXFnN1Gg1S/+Vm0H0NzwV18eA5g=,tag:/K2CAF1eGjE1CIYFP0W78w==,type:str]
    version: 3.13.1
