---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pihole

generatorOptions:
  disableNameSuffixHash: true

helmCharts:
  - name: app-template
    version: 5.0.1
    repo: https://bjw-s-labs.github.io/helm-charts
    valuesFile: values.yaml
    releaseName: pihole

resources:
  - ./secret.enc.yaml

patches:
- target:
    group: monitoring.coreos.com
    version: v1
    kind: ServiceMonitor
  patch: |-
    - op: remove
      path: /spec/namespaceSelector
# - target:
#     group: apps
#     version: v1
#     kind: Deployment
#   patch: |-
#     - op: remove
#       path: /spec/selector/matchLabels/app.kubernetes.io~1controller
#     - op: remove
#       path: /spec/selector/matchLabels/app.kubernetes.io~1instance
#     - op: remove
#       path: /spec/selector/matchLabels/app.kubernetes.io~1name
# - patch: |-
#     apiVersion: apps/v1
#     kind: Deployment
#     metadata:
#       name: pihole
#       namespace: pihole
#     spec:
#       selector:
#         matchLabels: { app: "pihole", release: "pihole" }
