# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/library/common/values.schema.json
controllers:
  pihole:
    replicas: 1
    strategy: RollingUpdate

    annotations:
      reloader.stakater.com/auto: "true"
    pod:
      dnsConfig:
        nameservers:
          - 127.0.0.1
          - 8.8.8.8
      dnsPolicy: "None"
    containers:
      pihole:
        image:
          repository: ghcr.io/pi-hole/pihole
          tag: 2026.05.0@sha256:70a9c11171ded2eee735d88c127996da209284a329d50f5ae59c06b861d401b3
        env:
          TZ: America/Vancouver
          # nebulasync doesn't like env variable configs
          # FTLCONF_dns_listeningMode: all
          FTLCONF_webserver_port: 80
          FTLCONF_webserver_api_password:
            valueFrom:
              secretKeyRef:
                key: password
                name: pihole-secrets
        probes:
          liveness:
            custom: true
            spec:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - curl --silent http://localhost/api/info/login | jq 'if (.dns | not) then halt_error(1) end'
              failureThreshold: 10
              initialDelaySeconds: 60
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            # looking at the query log can spike the memory usage very high
            memory: 512Mi

service:
  dns:
    forceRename: pihole
    controller: pihole
    type: LoadBalancer
    annotations:
      external-dns.alpha.kubernetes.io/hostname: "dns.g4v.dev"
      lbipam.cilium.io/ips: 172.16.10.211
    ports:
      client-udp:
        port: 67
        protocol: UDP
      dns-udp:
        port: 53
        protocol: UDP
      dns-tcp:
        port: 53
        protocol: TCP
  web:
    controller: pihole
    ports:
      http:
        primary: true
        port: 80
        protocol: HTTP
      https:
        port: 443
        protocol: HTTPS

route:
  app:
    enabled: true
    parentRefs:
      - name: http-gateway
        namespace: envoy-gateway
        sectionName: https
    hostnames:
      - 'pihole-bak.g4v.dev'
    rules:
      - matches:
        - path:
            type: PathPrefix
            value: /
        backendRefs:
          - identifier: web
            port: http

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 1G
    advancedMounts:
      pihole:
        pihole:
          - path: "/etc/pihole"
            subPath: "pihole"
