---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: step-ca

helmCharts:
  - name: step-issuer
    version: 1.11.0
    repo: https://smallstep.github.io/helm-charts
    valuesFile: values.yaml
    releaseName: step-issuer

resources:
  - ./secret.enc.yaml
