---
stepClusterIssuer:
  create: true
  caUrl: "https://ca.g4v.dev"
  caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJuRENDQVVHZ0F3SUJBZ0lRTXp1YUF1OGpsY0pwemUzc3N0THU4akFLQmdncWhrak9QUVFEQWpBc01SQXcKRGdZRFZRUUtFd2RITkZaRFpYSjBNUmd3RmdZRFZRUURFdzlITkZaRFpYSjBJRkp2YjNRZ1EwRXdIaGNOTWpZdwpPREV3TURVeE5UTXhXaGNOTXpZd09EQTNNRFV4TlRNeFdqQXNNUkF3RGdZRFZRUUtFd2RITkZaRFpYSjBNUmd3CkZnWURWUVFERXc5SE5GWkRaWEowSUZKdmIzUWdRMEV3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFUZTdlam9EVkdRS2tyRmk3THVncEllZG9hU0lPbjRKN2tEb0xndGp3d3E4SFFwVDdMYkZuMTJsRkZ2ck0zdQplVmVFTDVQQmN6UDlXYlZkVjBEQUE3M21vMFV3UXpBT0JnTlZIUThCQWY4RUJBTUNBUVl3RWdZRFZSMFRBUUgvCkJBZ3dCZ0VCL3dJQkFUQWRCZ05WSFE0RUZnUVVtaWxVd1NJeHZOQ3VZMG1remNvNURFcGF3eTB3Q2dZSUtvWkkKemowRUF3SURTUUF3UmdJaEFLWWhtL1FOeHdQd0IxTUJSZkJvTkVaa093ZWI0a1lhTWN1eHlEaHNWbEZEQWlFQQo0WWZlWHNvR0hnRkp1VEVtbjFZeFlZdWhjbjZ2OGQ2a3NxWGxJb3B3b3pnPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  provisioner:
    name: "ca@gavinmogan.com"
    kid: "s7mgcaL-wSc9GX9zbbbsN2TR9tZtFQNfYAdbpx7JUcM"
    passwordRef:
      name: "step-issuer"
      key: "password"

