apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: "nanoproxy.taildba47.ts.net"
    tailscale.com/hostname: do-home-socks-proxy
  name: home-socks-proxy
spec:
  externalName: unused
  type: ExternalName
