apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{.Release.Name}}-certificate"
spec:
  commonName: 'mumble.halkeye.net'
  dnsNames:
  - 'mumble.halkeye.net'
  issuerRef:
    kind: ClusterIssuer
    name: acme-letsencrypt-prod
    group: cert-manager.io
  secretName: "{{.Release.Name}}-tls"
