apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: mautrix-linkedin-sopssecret
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:1DYD/acEpRoUc3Y2C4e3gTJqsubHXn8=,iv:uclbAQnnzSaSE/dFU8rdqggJYkS8NrIsxGrCe878i3M=,tag:BSKzAJ5Ok3Sp8JOsSXO2rQ==,type:str]
          stringData:
            ENCRYPTION_PICKLE_KEY: ENC[AES256_GCM,data:OiWRuEVpcWk3rbyfYd90qGN2oEnU/T0Vu03Ska99+cqhzdfFSo2/XoCXmGxYrNd7Dm1t00xrw+Xl3xtJ02At0A==,iv:7dC2Sf4o0jfrCyJtMJ2SVWVrpOzvro4ViqICiZUAZOM=,tag:EETnFMWvuwE3K7HIY6Ox9g==,type:str]
            PROVISIONING_SHARED_SECRET: ENC[AES256_GCM,data:jy/TE3AWfVgvXEu8Mg79bYwiusHhnTPWcnRSNb2uBqvQZ0oTsdh/zyR5GjojhESxyl/AqJxPM7ZHD+w7ciSBFYTIPXHvbxn7i87BIuxQWgjGvhEGHiq9B05+1GGtS5a3wCnBTIF+o3u0bOyEbBP1KibbCd3Zsk2AaThZCeLqa7Q=,iv:dv3O9anh4efO8r49SmSg7gDeY1eW6L0BOCFjFw1ZhCE=,tag:aqEtYpEKDrsXBnmIR1ocCA==,type:str]
            SHARED_LOGIN_SHARED_SECRET: ENC[AES256_GCM,data:lAqwOHpYqwEClTBMBE73zSocYL2kEUESoQ9wSlHC/oV1z7b8kQz8FOg/AeEA4XgreGoOO8QGNcIhjt73gZ9o2YNkNMgMsuX/nuKPKePVvWLsDZd4hKxwhGT9LTQh+9F3zJH9kPUDFvjtL+MVjMFhuTsjDdRCS304suuc1T3i8X0=,iv:TRdOYyz8bYqRgQN+lNkU8xuNwT+Hf8YbwH6fR1oShzE=,tag:s+e0j4cW8avTZSFore/eLA==,type:str]
            LOGIN_SHARED_SECRET: ENC[AES256_GCM,data:ePUD4uBUo/EQoJ42EK/7S4sRnGkv5a5af3PC/WfffIro7BjpzPmq0/TpG9Y4rh1vGlULz1JCsHb0XgPRXp1DVMiCVJSin0z9Cg==,iv:Hdpzf3qykxMiGmRIaDlkdV+hlkwYL1/4fILpSPj0pXc=,tag:klIWBEbPkoX9Qxre9tniPg==,type:str]
            AS_TOKEN: ENC[AES256_GCM,data:Tdc9Fo5ub4663LUusNGIVrEBMst8M9b+TDxecYqFfIYhPxgNjbZQNk+D1FmjXzD7EyALhUKELkFI0dCaKWXRDw==,iv:AMEoXPen2aVMVFRg0vcDHE8C9lAzNvSMXlinVECnZts=,tag:q446K7DAoC1JNUJ9a1T2uw==,type:str]
            HS_TOKEN: ENC[AES256_GCM,data:6Hbv9EXAILJjV2+8xGY9FpOPLTCol8w9na5v8iKpNI0bdkzR9FVIt8uUO4LEQaNuxQV826FbyK6CjZaTDQOBAA==,iv:eVVANxgSmL8SYTVOg2Iw+3OuXy+0AilXqp7VfbLZUGI=,tag:ot54AG76ilv5tc+tWYXleQ==,type:str]
            PUBLIC_MEDIA_SIGNING_KEY: ENC[AES256_GCM,data:ZftyAg6lKEP5llZynKrOVJ/0FWtKLk69mKPZMIqyKq0NRXLHhdDMVBBFMp/Q9wXF8AqYbLOZ1qgDEg8BRpMHaA==,iv:KCy0BVh0PZQFt4EM5LPTPnHPpOaO7raEV9HxfDw1Gck=,tag:P9kUJUTPfPB6LRvdN/6Jkw==,type:str]
sops:
    age:
        - recipient: age1vqm5gwkmf38jsmt3j4lm3fdslausskaadtz360ewn0g7z2fchahqyr694v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOekZDaHoyZVV4WmJDVEFB
            bzZNbDZkeDJVV2pFWkppWGd0QU1XVmVIVm1ZCjZiZmNUTnFDeEI5ZzlpMmFaRGZU
            bWxKRVgxZE9pbUdoemM1VVd0Y0NBTkkKLS0tIG1Vd1VaMVgwaGZVKy9HMXZmNGdH
            VTdmZ3p4ZEN5R1BFVUxNdjUyV2F2emsKmrIe/w/meq050UARkrTF2RxJdC5D7Owa
            1+nPf2DThgDorPnnwxDeZ8LE32ceRhuh053+17+DZn571MW5gYUuvQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1aqel4n2xyfjmzjgey0mhxzhlmg2qd7xusjweku4w8u94dsq2gpmqye3wus
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ZDhDZGd2N2ZqbGNYU1ZM
            clJJY2hzL0w2anpJTmJaK0lQSjRDT3c3S0NZClNXODRLWHF2NlZxa29oZ2xvTzc2
            a0RZZ3g3dDlFUkkxYWZWdkVjTm42akkKLS0tIFpUWkZvL3J2ZjRXdVZZMFB2Rkdp
            VEN2d0lsQmNYeGNrZklGVHNuTGRPWkUKRkk2TJGhXdZ1ShyWqjSgOD4TswFQri2Q
            +N036LmuVWaCstoZg/2lUI9tyj4Yebw6ANeGgddRNkgu1mJBqZT0LA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y562y0u4k8y0eyq56s4g00ssd2cduamddcgfpu8fs7t00pfjss2s9nymt8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEM25PYUNacndSRXBLclhM
            ZEM4NHVwZVJTUnJhSzJMRSsvMHVvLzNFaWlZCnF3MlY5WHVhaHlKZml4OTdBMkho
            NHlpNVVFdnBYZVE1MUtkVy95UzZTZ0kKLS0tIDlvYnlNLzdhanU2TzdvUk11cFo3
            bXFzd2g4YS90NmlwKzcyQ3dwc0J4ZzAKRsre2BIsBEf5Cu5x9viVWn3okWTKZ9VQ
            W/cuz1Xi5y93URJttWJTth0lhapxMSsI4FaO9VYoVZpB16qN3gmQZQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lv53trxftjem0a4hewf9h9dmp65cql6ycaj5q8kvfnfspccg747s6lxpxg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXY09uM05VWmhJZjZWb1ZQ
            UXl3Yk1hZm16S2NhZFFxaVBZazRyRmZhOWhJCmpoL09ZYjRoVm9NSmx2UHAvaW5q
            M0lDbGtxSDUxdmZ4MmNGK1VWeW5EVjQKLS0tIG1DZW1aYTJrNEU1SGpidU5STmpn
            elRhcUQxK2F3SkNBYktWQ0hmYTd6cmMKW9m4vpqjCr5OoBHlDmezixIqOn6wlfjx
            MwGB1VN1/j3ufx8YWRwmUAoAXGnwUPwQRjdAZVjnDLpTeWBt25gQlA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ryqtmnakl6rc3z6qpqkhmw5pnsnzy2arwv7ecnh3ayf0za5pgtqft7lcn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUG9DUmJyUVFIdi9KMHZO
            R0NSb1ZESXVxV0hqcFBCVWtkckFOVnNBN1FrCjVBSSs2dGp5U21UWGVpKzNtYytn
            ZjcrcGxvTS9JN25tdjl5RDdRdGtTREkKLS0tIEtOOVpIU2RBKzgyMkhYVEFVMk5S
            ay9PNCt6OFowL091aDZaYmlBTzRGUUEKLku29kxyJ4eOnSvcWm3o5yPP3affZd3l
            XasVujTknUK5bXGHBDwtvd2yqPjU/MA7iGmUQSv0t1Z5P/J+TawEfw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFB0EXmaOVc61axVxDoWw1Y7JypG4LFFbS6+96dFY2VS
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGt0aTNnZyBTbG9Z
            TEE1QkhSbldKRDZJeVhrTzNwR2ZMenNQb0U0UVhTVHBoTm5tRldRCk9qSWZ5RElC
            OWJ3bkdWbnc1MlRYaDBuTHVWU2tvWSs3aTBvZ3F6SklIOTQKLS0tIGJsSUIwc0Y3
            cXFON3ZCcmYzUnQ0V2RaeUVTckxSUWZ6dnI3MDZXWUlsaVUK4SrHdXH3ox5bzIHK
            lOyqS5rFgkIR2Zl5JPK+LycvA8V+w9skyduPxmLrFsqD/gQG13OaR1hFORQcL92z
            6LTIeg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age179mmzgpy7ldyh3w6zld9vxjegxv80mkt6kffgg5enyquqrwnspkqv7sq7v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRmZqbzBvczRnQUFoc3ZV
            U1dCdUlBb05XRktvUmxTOGJGY2Zxd3ZyR1FFCkJzWlU0ZEx1RVVWYlI3YlBsQjV1
            THlQbGZKVzM5VjdCZmplWllHemJqUWMKLS0tIEZHR2pNT1FmcENwL1lqRTZOSnZS
            TzN0WGlGajR3eWthLzFkbVpmUnhNNk0K2FqZ6alD1zuyW+Ko5hRkM+DNuLj+lO5/
            t3M/WQPNGULThzp7xkhU8KacC2aeVYPO7p3hIaVGdyqFw1kQtWEtSA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k63d5ts2w8hfvdar7lan2qamhcgrjpfdv4um97q0ehjs553x4sysx08xcg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByYzdTYUNvbkd0WGVXamp3
            VUV3UVNXam9GTU9hbysvc2ZkOWVZSFRGMDJjClJrc0N6ODRzcEJzOU9FMmR0U1hD
            SjZRYkNXVDh3Z1hsVjdCZXVobEJobFUKLS0tIGhTS05iM05YWlpSenF1cEgrZnlr
            T1dZZ0NHM1RoZk1ORjJxVU5ZNERsZ2MKIZnl0MWdch45naGvfSxmbi2FD5NGJqHm
            Jfi8wd7ivmiWirjJ9Ne7RPuvzLlzQToY/w+uZooIsnPO37+WJl8KAg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mkkltp58ptsvn5t7x8anr4hy20z0z6568nsljfa7tmwx07ug09aqf6rxe6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbS8yaFJnRTNQSUVnNmJG
            Vm82TjVUTVdpdWoxMjNWVlN4bXFNb2tqZXhFCkNDMiszMjE3MnhobFVpb2IyQUNv
            TXMwWmU4TFo1dDhWMnJIYTE2TjZVVmsKLS0tIHFka2U4ejNHWi9LUm4rOGx3bEI5
            RmtvZEVoUzMzWnUwK0dxUmQ0S2N5Q0UKMxzZban2DaEdbr01q1IhsFwJFegRqpjV
            OwT2yFAjQUhAqbP2QQoUT7130SQ5D1WnG0AAO1ojMPboBem0NUZhpQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tfj0kfd2twsa655d5hx2afczlpcfzw7hapc07gr7ywnqq08qxdtsud2gfz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZTUwMStZYWtVdENYMkFl
            b2Z0YUk3aEtzMmlhNzdVQmFOTnBGOVJHaVFNClIxc0c0YXdSRXd3eXRLZE9zczlK
            YmorOGdKeDlPck9sb0hFdGFTeG1pNzQKLS0tIDdQOWNOTXR3TjlQKysvNzlDTUZx
            d2ZkcUdxZ2NqVGY5QWxTaVpWd0VuZ2sKRqwKo0YrBtzP3o7twRo0O2q09kVgRp2a
            fARELVvB6YIiMFMeMSE1fHyEBYCeR6GH3tMTDXz0jLgVRvyG57OX/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T03:18:59Z"
    mac: ENC[AES256_GCM,data:QcFjJO8BJqC7U81lnF/aPxQrZYLv9unllEqxqoyXw1gUt2ScuAuAJ0BUUUq5hm6UmPt9D8p5gLeddZH9uydTkPDyBXfQq58dslSwK1m73TMsdtHy6mX8cmChc0cXB2nODrCsIsulWCM7EEGkBNNWiFTD5aJ1YbKFlqqlu96faHg=,iv:e9VBN4rSfnPaEb/7hfL33w4QzRw6CWBPti8RCCSzhrQ=,tag:2qKXKW5ZH5vGeaox+u1RjA==,type:str]
    encrypted_suffix: Templates
    version: 3.12.2
