---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: step-certificates

helmCharts:
  - name: step-certificates
    version: 1.30.1
    repo: https://smallstep.github.io/helm-charts
    releaseName: step-certificates
    valuesFile: values.yaml

resources:
  - ./secret.enc.yaml
  - ./httproute.yaml
  - ./backendtlspolicy.yaml

patches:
  - target:
      kind: Service
      name: step-certificates
    patch: |-
      - op: add
        path: /spec/ports/0/appProtocol
        value: https
  - target:
      kind: StatefulSet
      name: step-certificates
    patch: |-
      - op: add
        path: /metadata/annotations/reloader.stakater.com~1auto
        value: "true"
