{
 "title": "External DNS",
 "description": "Grafana dashboard to display external-dns metrics",
 "tags": [
  "external-dns",
  "dns"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(kube_pod_info{job=~\".*external-dns.*\"}, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "external-dns endpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Endpoints in the registry",
   "type": "timeseries",
   "description": "Number of Endpoints in the registry",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "external_dns_registry_endpoints_total {job=~\".*external-dns.*\",job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Number of Endpoints in all sources",
   "type": "timeseries",
   "description": "Number of Endpoints in all sources",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "external_dns_source_endpoints_total {job=~\".*external-dns.*\",job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "external-dns sync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Timestamp of last attempted sync with the DNS provider",
   "type": "bargauge",
   "description": "Timestamp of last attempted sync with the DNS provider",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1000 * (external_dns_controller_last_reconcile_timestamp_seconds{job=~\".*external-dns.*\",pjob=~\"$job\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Timestamp of last successful sync with the DNS provider",
   "type": "bargauge",
   "description": "Timestamp of last successful sync with the DNS provider",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1000 * (external_dns_controller_last_sync_timestamp_seconds{job=~\".*external-dns.*\",job=~\"$job\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "external-dns controller no_op runs total",
   "type": "gauge",
   "description": "external-dns controller no_op runs total",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "external_dns_controller_no_op_runs_total {job=~\".*external-dns.*\",job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "external-dns records", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Number of A records in registry",
   "type": "gauge",
   "description": "Number of A records in registry",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "external_dns_registry_a_records {job=~\".*external-dns.*\",job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Number of AAAA records in registry",
   "type": "gauge",
   "description": "Number of AAAA records in registry",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "external_dns_registry_aaaa_records {job=~\".*external-dns.*\",job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Number of A records in source",
   "type": "gauge",
   "description": "Number of A records in source",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "external_dns_source_a_records {job=~\".*external-dns.*\",job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Number of AAAA records in source",
   "type": "gauge",
   "description": "Number of AAAA records in source",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "external_dns_source_aaaa_records {job=~\".*external-dns.*\",job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Number of DNS A-records that exists both in source and registry",
   "type": "gauge",
   "description": "Number of DNS A-records that exists both in source and registry",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "external_dns_controller_verified_a_records {job=~\".*external-dns.*\",job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Number of DNS AAAA-records that exists both in source and registry",
   "type": "gauge",
   "description": "Number of DNS AAAA-records that exists both in source and registry",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "external_dns_controller_verified_aaaa_records {job=~\".*external-dns.*\",job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "external-dns errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Total external-dns registry errors",
   "type": "gauge",
   "description": "Number of Registry errors",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "external_dns_registry_errors_total {job=~\".*external-dns.*\",job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total external-dns source errors",
   "type": "gauge",
   "description": "Number of Source errors",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "external_dns_source_errors_total {job=~\".*external-dns.*\",job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "external-dns job", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum(node_namespace_job:container_cpu_usage_seconds_total:sum_irate{job=~\".*external-dns.*\",job=~\"$job\"}) by (job)",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "scalar(kube_resourcequota{job=~\".*external-dns.*\",job=~\"$job\", type=\"hard\",resource=\"requests.cpu\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_resourcequota{job=~\".*external-dns.*\",job=~\"$job\", type=\"hard\",resource=\"limits.cpu\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=~\".*external-dns.*\",job=~\"$job\",container!=\"\", image!=\"\"}) by (job)",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "scalar(kube_resourcequota{job=~\".*external-dns.*\", type=\"hard\",resource=\"requests.memory\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_resourcequota{job=~\".*external-dns.*\",job=~\"$job\",type=\"hard\",resource=\"limits.memory\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_job:container_cpu_usage_seconds_total:sum_irate{job=~\".*external-dns.*\",job=~\"$job\"}) by (job)"
    },
    {
     "expr": "sum(kube_pod{job=~\".*external-dns.*\",job=~\"$job\",resource=\"cpu\"}) by (job)"
    },
    {
     "expr": "sum(node_namespace_job:container_cpu_usage_seconds_total:sum_irate{job=~\".*external-dns.*\",job=~\"$job\"}) by (job) / sum(kube_pod{job=~\".*external-dns.*\",job=~\"$job\",resource=\"cpu\"}) by (job)"
    },
    {
     "expr": "sum(kube_pod{job=~\".*external-dns.*\",job=~\"$job\",resource=\"cpu\"}) by (job)"
    },
    {
     "expr": "sum(node_namespace_job:container_cpu_usage_seconds_total:sum_irate{job=~\".*external-dns.*\",job=~\"$job\"}) by (job) / sum(kube_pod{job=~\".*external-dns.*\",job=~\"$job\",resource=\"cpu\"}) by (job)"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=~\".*external-dns.*\",job=~\"$job\",container!=\"\", image!=\"\"}) by (job)"
    },
    {
     "expr": "sum(kube_pod{job=~\".*external-dns.*\",job=~\"$job\",resource=\"memory\"}) by (job)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{job=~\".*external-dns.*\",job=~\"$job\",container!=\"\", image!=\"\"}) by (job) / sum(kube_pod{job=~\".*external-dns.*\",job=~\"$job\",resource=\"memory\"}) by (job)"
    },
    {
     "expr": "sum(kube_pod{job=~\".*external-dns.*\",job=~\"$job\", resource=\"memory\"}) by (job)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{job=~\".*external-dns.*\",job=~\"$job\",container!=\"\", image!=\"\"}) by (job) / sum(kube_pod{job=~\".*external-dns.*\",job=~\"$job\",resource=\"memory\"}) by (job)"
    },
    {
     "expr": "sum(container_memory_rss{job=~\".*external-dns.*\",job=~\"$job\",container!=\"\"}) by (job)"
    },
    {
     "expr": "sum(container_memory_cache{job=~\".*external-dns.*\",job=~\"$job\",container!=\"\"}) by (job)"
    },
    {
     "expr": "sum(container_memory_swap{job=~\".*external-dns.*\",job=~\"$job\",container!=\"\"}) by (job)"
    }
   ]
  }
 ]
}