apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: authentik
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:ZiNQyl1hz6vW,iv:I8IeEsBq2GDucUgRJSUzD8GRcAFziQCsUvRsJTijteM=,tag:ezIMchCcddyPv91AD4kosg==,type:str]
          stringData:
            AUTHENTIK_EMAIL__FROM: ENC[AES256_GCM,data:f3WlKZ/uIz5bBOJi9IDUJ8E=,iv:E+nOdO6No6TOru3pwC4a5ZNTm69CJH9IrjEKYr2U7m0=,tag:kPH/5CAuGX/Q7FMbsYXMHQ==,type:str]
            AUTHENTIK_EMAIL__HOST: ENC[AES256_GCM,data:fpGmtn6rpW1wvYQJOyabZUlZm83SvWD1JB7HKF9pSa5bNchpGoMj,iv:KrBgWx1/0D5UJMXiD4JDseV1+TKL+Lw4s3dDPNbsH7A=,tag:PCEyhFTMIe+BZykY6a5yCg==,type:str]
            AUTHENTIK_EMAIL__PORT: ENC[AES256_GCM,data:dtKeSw==,iv:hbbLDnD88j3g2ASTlSY4oOO+CZR+T0VWGNfUEsPDfNo=,tag:cloqpEBQCBKEXvijQJXO+Q==,type:str]
            AUTHENTIK_EMAIL__TIMEOUT: ENC[AES256_GCM,data:u3w=,iv:3qT8LT+759heD0rU2yxAtaGw1dRslS8a2jpANysW5UU=,tag:1DL44FtNKyr3oPJCp1cLxA==,type:str]
            AUTHENTIK_EMAIL__USE_SSL: ENC[AES256_GCM,data:j8YJf18=,iv:f0c1HmjecIWwRtJOxpq4MwrPIGVyNt71AJ2jxRiuUfU=,tag:N8WfcGfub++V9wBdcaBLRA==,type:str]
            AUTHENTIK_EMAIL__USE_TLS: ENC[AES256_GCM,data:JNnw+Gg=,iv:auDDel0FuQI1MguC/Q+CTmyLKeIgH+p67sbuDLTVoZk=,tag:eAhtgyv/c+HV1b5R6FH7fg==,type:str]
            AUTHENTIK_ENABLED: ENC[AES256_GCM,data:rAS/CQ==,iv:5SOhlQLJCTwHO5p0grqWowrg5RkPP4hzOTJ5AaiKFhU=,tag:xpNgEEmGWHb0iMlqMZsVEA==,type:str]
            AUTHENTIK_ERROR_REPORTING__ENABLED: ENC[AES256_GCM,data:QnL9Zw==,iv:NxJX5hboZJAsZOiXALW8DPWq+8WfuLT629SvIR+12jo=,tag:po7ZlxTGTosh4Mf4ANeP3g==,type:str]
            AUTHENTIK_ERROR_REPORTING__ENVIRONMENT: ENC[AES256_GCM,data:xgUA,iv:dkVeZ4gmOjWtUKOC9Rn1Nt/v3Cy/asBhoDgpdyhGCUE=,tag:vtkrc8SlutuIM+bHVZnIng==,type:str]
            AUTHENTIK_ERROR_REPORTING__SEND_PII: ENC[AES256_GCM,data:Pucd19s=,iv:J6aN1BSIJmKOVrKTHbruYZQeKijf1SI4nnoH9pNd2v4=,tag:+HcQb0WxOFf4qHyWBudyQg==,type:str]
            AUTHENTIK_EVENTS__CONTEXT_PROCESSORS__ASN: ENC[AES256_GCM,data:7rhksO3/oh/e8VKVmloFsb3ayz2OBqCB,iv:8I7nqJa7S2ZQ5u2wDN6gSVzbokpVkI/cdVxab6xMG6w=,tag:Y7NqpFElpbDh6kFgBoxUdA==,type:str]
            AUTHENTIK_EVENTS__CONTEXT_PROCESSORS__GEOIP: ENC[AES256_GCM,data:ZT2e2xb0714J3I6n+2fOSkPby3VTyjKWwA==,iv:y801bFYvbs6HGocSXHLfzFqfVodWrGEVotKKhP5FPyU=,tag:XTvYXWF24at6UyOo837f5w==,type:str]
            AUTHENTIK_LOG_LEVEL: ENC[AES256_GCM,data:T+ujEg==,iv:BRUYU8IDKrI6oN3w0Rg1Tu51SVdU/wSDWiJ5fThtQow=,tag:uVBAK6jdeWNrg3sGBImRxw==,type:str]
            AUTHENTIK_OUTPOSTS__CONTAINER_IMAGE_BASE: ENC[AES256_GCM,data:+OfcwN8i6TUHq8hLy2i+pfa0B/GrwiRSiN2BVLNw7RuWPqrkHhwR4w==,iv:sML8oO12DF7+AyVevItsqCIfZz4RUfQkgfLrALRS0Kk=,tag:3wpFvIYqyfVBixKgM/4C9Q==,type:str]
            AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:FMOHw62tkMcV330AN7NorUabOSwaHIt/Q2Qm2nfvBGBFEJEGcwgZMBlXIm91kyYo+oXzDg==,iv:kTOiarnEIblvqT02et2NA2VKqj0cMjBUtOIdjrb5w68=,tag:tuvhvxmC7vtZEQbPCAOqFg==,type:str]
            AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:s8ZyhxzFf0E8,iv:2Pod8uNbQ9CHfFksNoihVzYZH1faRgrXJrg/TxO3fIA=,tag:RlzmDg0DxeT8IkmVDPx3xw==,type:str]
            AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:0IlztM/JaLP7cTIEer4uizeCFEis3mQ1,iv:pmETBPKGw/rQQ083Y9XeqYvYHpCpRO+bEk6FQe0dAMg=,tag:U5p17vsmcqETuU9lLeNDyg==,type:str]
            AUTHENTIK_POSTGRESQL__PORT: ENC[AES256_GCM,data:YBaTpwk=,iv:kd5LAprvqeFOQ8s/J0RrdSr5R1q/87MPy2qiFUnneAw=,tag:ESXq+Af/K50lc04UvWC1gQ==,type:str]
            AUTHENTIK_POSTGRESQL__SSLMODE: ENC[AES256_GCM,data:kwy2OJZ3Wg==,iv:HERNy0c4mLBsw0JoNN6cLaco1R3hJTbQF3iuNiQXMOo=,tag:4zO9xO1EsyXZt9K7m1QeHw==,type:str]
            AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:F4b4xKg6gMTW,iv:3SaiVY4r+5LGUf98lClsDXhNjgLVv/ABn6fDVmNGCqs=,tag:QGiNse7u5VUkX3R0KC6esQ==,type:str]
            AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:6Qh4RuQKeCkOtnjwGJzWWXh3dQTj4sbN9UhrvABK+jJ3Vga8,iv:HRnLXuHRMmox69xWZJvncBLVAMpmTSI7aigKiJKk3aY=,tag:OLHPp7gV7ittKcbUUVZVdg==,type:str]
            AUTHENTIK_WEB__PATH: ENC[AES256_GCM,data:Yg==,iv:7k/ayzY+kqdIcOIBUBLbB47RlHHmYRMZH4WC51jf9SA=,tag:a9Rg/gB02YESW0cJrSu/MA==,type:str]
            GEOIPUPDATE_ACCOUNT_ID: ENC[AES256_GCM,data:O17yBPYP,iv:VMmbpiwzgTw/jkeUeBa2DsXPAdFL7JQa5QtZq4CrhJc=,tag:75aD/3VmmQLWk/s5uHQB9g==,type:str]
            GEOIPUPDATE_LICENSE_KEY: ENC[AES256_GCM,data:xfgtGAwPKzZhWRxbEOrU0Q==,iv:Nybr9JpCira3z1ZdQUPqOd2BcvDD7Z/HX31nS0zXQUo=,tag:EHhskjr/Fs8Ji7th3+245A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicEw0TlF4ekZvYy9ncnJu
            ZkZIV2lLSk92Y09oRVNPU3pMZC9nMzFyekNNCnBnRVZBT2cxcXREVGdHMmRrdFJ1
            UDhPL0VlaXVOTEpuTTVGLzErNWRGOFEKLS0tIHByUEZTbUJNcnA2amltck1zWWp4
            M01Cbkg3SnF0OTVZWG9QS1c3bENNRDQKq9ThB0G9dZOHiyJHZPvy6P41qDpa5xNe
            oW7tRVyoxjlJqsJtg4vVeKsnQQEfQZ1zN/J0jrs1cjqzxLPMYKDi0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vqm5gwkmf38jsmt3j4lm3fdslausskaadtz360ewn0g7z2fchahqyr694v
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqd21yL1NsZVZyVlkweTJM
            aE5wOGNvWTNJMWdYaTJYNnRmQi9WTXBEbW5vCkJrNHhzVTJMbnVEUlU2MVRYbVgz
            WlBFRkNwa3pDQVRsbWRWODF1VUtVem8KLS0tIFQvaDZBYy9kczh0MllOMi94YWZP
            MHI2WkFNMEYzWHRSa0xFeTBPNHlIL0UKGw8Q/ebh38HNkglyKKVFVzfSbZvvM/UC
            Fsox9urJaj3mWoFRgW8hy1MtNpNgYSAD09w6I2mbrDS+Xpp0FHgX5Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1aqel4n2xyfjmzjgey0mhxzhlmg2qd7xusjweku4w8u94dsq2gpmqye3wus
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMV096QVdVNGtlazNiQjlq
            VEIrUE9TVEdRZ0pVUURmZ2phSXFxcldNblJvCkUzQkxMRnBkRUo3N0pKVzhSRmY3
            RGF5NjlBaG4vWkxIRHZtVlVOWXNQU2sKLS0tIGVUak9RWEFuSXVabkhxb0h5MWNq
            L0MrNjA1NlFWQW1KQ0Fuek10VC84bncKAXctf7jFJ7RkpzDadG20QLv7GrZaQZva
            6gXSlT05EUm/kGYKErpnegOlLHH7GvuE/vVn1SCV9hfqdUfhY7MG1g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y562y0u4k8y0eyq56s4g00ssd2cduamddcgfpu8fs7t00pfjss2s9nymt8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwYjJJVFNSZDJjZ2FyZitW
            eXNicHMzYTIzK1lvQnNTVGV0dXNraEtkdFFJCjZqY3VCQ1FTMGYzZmxObStDblZD
            OCtIdHBZOFNUbHp0TFBzMkNpSG85M3MKLS0tIHVrSFdLN2Z0b3duTENxZXVQZzBL
            c0NrbEQ4RjJ3SzRXZ1ZEUzRkeWluQnMKAyc6HwOELfkhD6hJY63GAMjR+gIpJ5b8
            UJ6HL0bwZBqPPTsdCYVgFLs1CsilSrZirzKrsFmyyn7MryPMLqA+Wg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lv53trxftjem0a4hewf9h9dmp65cql6ycaj5q8kvfnfspccg747s6lxpxg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjT3EvZE9lcmZEa1JVZ3BV
            TzkxL05zbzFsc1Azeld2YkdUR0lCcVJpeG1JCjVsUDdEaFREMGFpemFWd21EUzEy
            b1dPNlQwakVIWmNSNzJsblZsRExxNjAKLS0tIFdCR09xeVc5Uk1oVkY0MVIzZ3NP
            SkNNVUxkeldpTGVvbW1Hd0VVQWZXaU0K8cXD1oz8Nq++i2+TkksbplqRj1PHJYyu
            0Q55RQWQvhxLjgL4GGrM3zAYPT+7QQL2ZC8Ypou8Q837py9lQ8gUGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17ryqtmnakl6rc3z6qpqkhmw5pnsnzy2arwv7ecnh3ayf0za5pgtqft7lcn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGt0aTNnZyBGdVBY
            Y2pHTGRSYzdnUGpoMkVhTzl2Yzl5RU1uTE0xL3JBWno5VTVOT21ZClU2M3k2TVUy
            cUpSb2xHTUZ4Z3VJVUZtdys2bDhaaHR6TEJscHV3VFJDZkEKLS0tIDVaMFNBMm5p
            NktlVVZHRHh4Sml2UHA0N1Q4dEFzdEFsOUx4bUJFQWNxTDgKrHh4uyFfrL1pTDaA
            HwKkAIhAgEer7H6L/VEai+3/BjmZKGl56rPYapRPixiH6A50w6Ts7izpybKPvDMA
            4OUg4w==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFB0EXmaOVc61axVxDoWw1Y7JypG4LFFbS6+96dFY2VS
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAza2V5VDdMd3pxTy9mbG5Z
            eUFEUzMyS2RxSUsvWS9KWlNyS3BtdmR1YUMwCmRkN3N6OFZnZVczM216cTVBV1JZ
            MEx4YlM4TmpEV0lRdFNibWNvWkhpaDgKLS0tIG5Ddno5dzQvYkt2YVMwekdqbjVR
            V1RTa3VRSWJ2UkVnUnp0cGtVWW5zOXcK3tKnKg8+C2icoFNi16t5e9kV76jE14hu
            s3UwcHPbG3S2lQCbSfELV+fjU6M1PHj+X8+wTU8pqisMW91Cs1XQYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age179mmzgpy7ldyh3w6zld9vxjegxv80mkt6kffgg5enyquqrwnspkqv7sq7v
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUFRNMHRucVU3bnFBT2dy
            d1RJcEIrZzY2VldJZzlMcitodG5keThDdkNnClFsM0w5RFpYMmc4VTJHczc2ckpF
            eVdsdUFZUHpqbXhLWVpDNTZ2N2Era2sKLS0tIGZGcVlpZFh6d2ZjZzJXWG9kejVJ
            THlCM0wxRGYxak14TW9QTWswdFpEcmcK3mh/Q8vy7IgiQNqwyY0E5ALjha/2IzjF
            NKzMFMyADn7wOnV4WqwP7RIHZBD8AUEv1LbiresAoaF/nJZlSin6EQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k63d5ts2w8hfvdar7lan2qamhcgrjpfdv4um97q0ehjs553x4sysx08xcg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBia3lEM3VqWDdFYUVxRkhr
            YlpwSjdZMkNoK1JVRlAxcjAvSDVSSWJCb1dvCjMzYi81aWFnSVFwZCt2SFlCdXVQ
            SU5wZTJIYjNBMVhuN2kxdjlBZHBPQUUKLS0tIHZiV3VZT0s3ZW9UcUJuZU1hMHdx
            ZzhEOW52WmY1UzB0NHY0Y0dXTUYwVTQKNFNUJfDXB0WgF7kg0vtPPcqgDjyUmN9b
            44ZZxSzGjZN0We2l+IqOgQm7UhD0HcK+VjE64+hDX1M4u286OBzB7w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mkkltp58ptsvn5t7x8anr4hy20z0z6568nsljfa7tmwx07ug09aqf6rxe6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZlQ2bUxObStLSmNuNGh6
            bVpRYktMLzNEZWpkR3F1T25Wb0c3T05ZY0VFCnZOL3BCTGRZUHhQb1lKM0V5ZHhv
            dlZJZjJCQXpvT2FSQnNlL25xemNFODgKLS0tIEdqTVBTR2RML25GSFhHb3IzdStO
            MVlUUVhURDFhbitheGpCZUVZcGJkZWcKYx/TI/Pt4OH2t2b2v/M5SrZ21Gp1frDC
            OUCY/aT6GuGSE9RpDFLLLsBdSRQ39709aRL8bJYuXtGIBbh/Uuby4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tfj0kfd2twsa655d5hx2afczlpcfzw7hapc07gr7ywnqq08qxdtsud2gfz
    encrypted_suffix: Templates
    lastmodified: "2026-06-09T05:30:43Z"
    mac: ENC[AES256_GCM,data:BS+mEu+VZaMYvIVWrbNfiXacKD6eorT5+0voBPHZjZZ7X0/lwlUjd0qKi/Bj7CYXATXa+JiXt27nh+brbj/LIEPrs2uE2UrDc4ZrFV1UXMDKAp6DPtEEDn5RtQXbB6+ZpFot7KF9YL0JJAhcnMDa7UBbBO4UjVZMNxk+QeGgk8g=,iv:n5F7tRzdwhaXHliHN6KgU80Zz65RZxldt/j22eCxagk=,tag:1Vru/cyYPOsNM08ZY2n+FQ==,type:str]
    version: 3.13.1
