---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/library/common/values.schema.json
defaultPodOptions:
  enableServiceLinks: false
  securityContext:
    runAsUser: 1026
    runAsGroup: 100
    runAsNonRoot: true
    fsGroup: 100
    fsGroupChangePolicy: "OnRootMismatch"

controllers:
  oauth2proxy:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      oauth2proxy:
        image: 
          repository: quay.io/oauth2-proxy/oauth2-proxy
          tag: v7.15.1
        command:
          - oauth2-proxy
          - --alpha-config
          - /data/oauth2_proxy.cfg
        env:
          OAUTH2_PROXY_EMAIL_DOMAINS: '*'
          OAUTH2_PROXY_SILENCE_PING_LOGGING: "true"
          OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
        envFrom:
          - secretRef:
              name: navidrome-oauth2-proxy
        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
        resources:
          limits:
            memory: 110Mi
          requests:
            cpu: 30m
            memory: 110Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
  navidrome:
    annotations:
      reloader.stakater.com/auto: "true"
      # litestream: enabled
    containers:
      navidrome:
        image:
          repository: ghcr.io/navidrome/navidrome
          tag: 0.60.3
        env:
          TZ: America/Vancouver
          ND_DATAFOLDER: /config
        envFrom:
          - secretRef:
              name: navidrome-secret
        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
        resources:
          requests:
            cpu: 10m
            memory: 250Mi
          limits:
            memory: 1Gi

service:
  navidrome:
    controller: navidrome
    ports:
      http:
        port: 4533
  oauth2proxy:
    controller: oauth2proxy
    ports:
      oauth:
        port: 4180

route:
  main:
    enabled: true
    parentRefs:
      - name: http-gateway
        namespace: envoy-gateway
        sectionName: https
    hostnames:
      - "navidrome.g4v.dev"
    rules:
      - matches:
        - path:
            type: PathPrefix
            value: /
        backendRefs:
          - identifier: oauth2proxy
            port: oauth
      - matches:
        - path:
            type: PathPrefix
            value: /share/
        backendRefs:
          - identifier: navidrome
            port: http
      - matches:
        - path:
            type: PathPrefix
            value: /rest/
        backendRefs:
          - identifier: navidrome
            port: http

persistence:
  data:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 10Gi
    advancedMounts:
      navidrome:
        navidrome:
        - path: /config
  music:
    type: nfs
    server: 172.16.10.10
    path: /volume1/Audio/Music
    advancedMounts:
      navidrome:
        navidrome:
          - path: /music
  audio:
    type: nfs
    server: 172.16.10.10
    path: /volume1/Audio
    advancedMounts:
      navidrome:
        navidrome:
          - path: /audio
  configmap:
    type: configMap
    name: navidrome-configmap
    globalMounts:
      - path: /data/navidrome.toml
        subPath: navidrome.toml
        readOnly: true
      - path: /data/oauth2_proxy.cfg
        subPath: oauth2_proxy.cfg
        readOnly: true
  # litestream-configmap:
  #   type: configMap
  #   name: litestream-configmap
  #   globalMounts: []
