controllers:
  valkey:
    type: statefulset
    containers:
      valkey:
        image:
          repository: ghcr.io/valkey-io/valkey
          tag: 9.0.3-alpine@sha256:e1095c6c76ee982cb2d1e07edbb7fb2a53606630a1d810d5a47c9f646b708bf5
      exporter:
        image:
          repository: ghcr.io/oliver006/redis_exporter
          tag: v1.83.0
        securityContext:
          runAsUser: 59000
          runAsGroup: 59000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            cpu: 100m
            memory: 100Mi

persistence:
  data:
    type: emptyDir

service:
  valkey:
    controller: valkey
    ports:
      valkey:
        port: 6379
      metrics:
        port: 9121

serviceMonitor:
  valkey:
    enabled: true
    serviceName: valkey
    endpoints:
      - port: metrics
        scheme: http
        path: /metrics
        relabelings:
        - sourceLabels: [__meta_kubernetes_pod_name]
          action: replace
          targetLabel: instance
          regex: (.*valkey.*)
