# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/library/common/values.schema.json
defaultPodOptions:
  securityContext:
    runAsUser: 1026
    runAsGroup: 100
    runAsNonRoot: true
    fsGroup: 100
    fsGroupChangePolicy: OnRootMismatch

controllers:
  main:
    strategy: Recreate
    containers:
      pinchflat:
        image:
          repository: ghcr.io/kieraneglin/pinchflat
          tag: v2025.6.6
        env:
          TZ: America/Vancouver
          TZ_DATA_DIR: /tmp/elixir_tz_data
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthcheck
                port: 8945
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
          startup:
            enabled: false
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
        resources:
          limits:
            memory: 4Gi
          requests:
            memory: 256Mi
            cpu: 10m

service:
  main:
    controller: main
    ports:
      http:
        port: 8945

route:
  main:
    enabled: true
    parentRefs:
      - name: http-gateway
        namespace: envoy-gateway
        sectionName: https
    hostnames:
      - "pinchflat.g4v.dev"
    rules:
      - matches:
        - path:
            type: PathPrefix
            value: /
        backendRefs:
          - identifier: main
            port: http

persistence:
  yt-dlp:
    type: emptyDir
    globalMounts:
      - path: /etc/yt-dlp
  config:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    suffix: config
    size: 1Gi
    storageClass: longhorn
  downloads:
    enabled: true
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: nas-apps
  music:
    enabled: true
    type: nfs
    server: 172.16.10.10
    path: /volume1/Audio/Music
    globalMounts:
      - path: /downloads/music
  webseries:
    type: nfs
    server: 172.16.10.10
    path: /volume1/Webseries
    globalMounts:
      - path: /downloads/webseries
  tmp:
    type: emptyDir
