---
apiVersion: mysql.operator.luktom.net/v1
kind: MysqlDatabase
metadata:
  name: ccnet-db
spec:
  dropOnDelete: false
  clusterRef:
    name: mysqlcluster
---
apiVersion: mysql.operator.luktom.net/v1
kind: MysqlDatabase
metadata:
  name: seafile-db
spec:
  dropOnDelete: false
  clusterRef:
    name: mysqlcluster
---
apiVersion: mysql.operator.luktom.net/v1
kind: MysqlDatabase
metadata:
  name: seahub-db
spec:
  dropOnDelete: false
  clusterRef:
    name: mysqlcluster
---
apiVersion: mysql.operator.luktom.net/v1
kind: MysqlUser
metadata:
  name: seafile
spec:
  clusterRef:
    name: mysqlcluster
  privileges: "ccnet-db.*:*/seafile-db.*:*/seahub-db.*:*"
