apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: do-k8s-ext-mysql-operator-sopssecret
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:Bbt3o5k/qFfa/moT,iv:8VnEwXZTAGoVC00yWAQw3BOmnQsfn2StRrGFJcKcvDM=,tag:KejVIsnIkJt2Z0jgFF5cNA==,type:str]
          stringData:
            JWT_PRIVATE_KEY: ENC[AES256_GCM,data:vZgjM4oZrKpPMcdsZdXO7OKpcZNCl1AnlJBzh3AIY+z+JsP3ARTGcOfA8OZhgNc+IRF/aEk5laOLu8XU6KUoAA==,iv:9n67LED2VaBEAtcJt05vmea/w8q2ubpydpj1R2xX3QY=,tag:lQhUIAz3LyU6pLxPdgIB5g==,type:str]
            INIT_SEAFILE_ADMIN_EMAIL: ENC[AES256_GCM,data:BPP3T9UOND0qqoFDlKrRzCShbbE=,iv:x6ZSJdHWI1NDPa4cYxbTNJNqRPmZ2pihQEaIHvve08k=,tag:yi1frMKg3NDsAkHp52pZ3Q==,type:str]
            INIT_SEAFILE_ADMIN_PASSWORD: ENC[AES256_GCM,data:+aN1TRk3tqSEL6EHrG2jGypbD5jEJqYKW7BZEKxthO7C93grINEkCVAny4Fp4jEKJneZ/0gWOoWjlTNniIRuvw==,iv:FvxUQV2Aq2oR7E0/VNBgfbS6Gr0bmIfwzLVUEC0D39c=,tag:PPixAZANA2fAWqcuxIW0SQ==,type:str]
            DB_ROOT_PASSWD: null
            SEAFILE_MYSQL_DB_PASSWORD: null
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bG9ibVJDaWt2SUxJNWRl
            cDV6aHFlK0tsVzNJNndJaUd5YmIrWkppcHlnCjJRNFBSMDg1RXZJL2Z6NEZhMVJv
            R1FmRWc0aUM5cUlweGJjMEtxTDQzUXMKLS0tICtOekZ3SDdUdlNSQ2ZlZGQxRTA1
            ZjZWYS9DV0dwbHpieHFjVG82RjNxYTQKAqnHF7ehO1B+kicEuBdpZxgzinQANUci
            N4m+oLCiq5eYmaME2jlyhGGMg7ieyQ9Z4OB7y9CgLC8ZxxKi0bslqg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vqm5gwkmf38jsmt3j4lm3fdslausskaadtz360ewn0g7z2fchahqyr694v
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bXByVXZrZEpUZVlxaG95
            YkV6YUIyQ1BTdkgwQXNhamwwSVhPOXZLYjJZClZCYlU3WEx6YzNPdmRkanlGYlNU
            Tm1rL2JzT1NTajFVWWorNHBvNkpDWE0KLS0tIDI2UlFDS2Y3U05jdDl4dWZYZ0dj
            S2dVWWg2L29zRmNRdXNyZWU5Z0ZreHMK8TV2/fO+0I8e0E7inNLNePyb5195g2gS
            82uJuj+L1ZdklqQvCssPWpWs60DqBwDVATp5cf8vCfz/7PoVxXFv+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1aqel4n2xyfjmzjgey0mhxzhlmg2qd7xusjweku4w8u94dsq2gpmqye3wus
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhc2FLTlNPcklrUGJNNkl2
            S0RyUXNaVnN6WG5ZQzQ4d2dqOEZUWnpBQVRJCmkyRTA4UWFxRlBmWGZzdHgyaGth
            SzNXamN3NS9UMWJwUG9IWGl2akp3Z0kKLS0tIFd0Y0IxMjVmZjZzcHUyRFhBcUMv
            WVVrZVNYY3FBN0J6bGx3ZC9mc01EdmMKpnS+nl2UTW7MbjJ26jh3uVv3/kdXUIde
            uBwvj5DUR+GQx0hrKMZ5OMUNW2zkKGyBHQdTYsFpKKUPneLLN/hOzA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y562y0u4k8y0eyq56s4g00ssd2cduamddcgfpu8fs7t00pfjss2s9nymt8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvK0pEQ3FWaGkrRWZzZFNC
            Rjg0dDk5eWhrRUd2alJKQVJLZjRwbERMK1Y0CllxWjh2QzFvcUlkdjJVMGtiMko0
            SXUwMGJzZUdPamd2WnFaWmVVYmZyQncKLS0tIGFGSDl5ZkpNeE5vdmVmZWtsaWVk
            TDZBWWpMK2hwaXduYnp1Y3dDOGRqUTQKeIDUoYI8jL0iVZ/lHSHqp8V0tjoogjuN
            klYvk1w05bON7aiwJVP72YXCJYFL7DtOfoJ993LtEAUZsP7kum4+BQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lv53trxftjem0a4hewf9h9dmp65cql6ycaj5q8kvfnfspccg747s6lxpxg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicnFXU3JYZzQ2KzFVSDdl
            SkF3RjZGWkNESlpPQllyeVBJbHdkcHROL0RFCndnMWxIZUpUbkpkd2k0UzBXbSth
            Umg5eWV6MldCOFBraWJ5bkNjZUQ2NE0KLS0tIHcxWHhRSlcxMTdzMXdFYkNDcFZI
            TVZGRHQ1WDdOOU1LNStsaXVvUURraVEK47cj6HqZQCNMUnvE8yRPJMY4OGaUCGoC
            E450EGlkEk4tcmn1hMF+Dppt/Qez84JLm0o+qeKH9MftrOSYUNW84w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17ryqtmnakl6rc3z6qpqkhmw5pnsnzy2arwv7ecnh3ayf0za5pgtqft7lcn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGt0aTNnZyBJWU1x
            T0h3NHB3ZUVFdmJ0aG13VHlDNkN6QjJaMjJsVTJNUDE4ellsWVcwCmhkb3JlQ1FI
            blBJeW92TVdSbGZNVXJIaGlrOVpVQ24xYVZoRmI1UWg2MG8KLS0tIEJJWnJDdWsr
            UTBmQTVoUjZuT3RsQjFZNTJoTlhnckU5RmVPNElxTkZGczAKE2ArhJbghcNbwb3c
            /aMu9HBkYLszClXqa4wYLJZVzJDQcUCjkVJFVpcy2/tsY3mCJv1JH7VfmcS7gx4J
            ML2AUA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFB0EXmaOVc61axVxDoWw1Y7JypG4LFFbS6+96dFY2VS
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJOW91NVpoTk4ySFdLa2Mv
            L0dPSXlTR1JtOGpTbmtaV200TWdmOHpnWkVRCkJmcW9qUjFhbmtIUEkvTFFheGEv
            bU1FSUV5SEVoTmhVZ0xDOWhLWG1tVVkKLS0tIFNNTm1EYWFpWVNyMjVUTHBHSXVq
            UlF6YUxmUUVuSnQxUVgvenlEMWpDS0kKPxlhKOI38hgPDdwb4a/bl4GIOU31AADF
            SrZRNudze+gtCR3pCiWB3jaU3m5nwqI3D+/EhAtYk39eJ9Oin+ukRQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age179mmzgpy7ldyh3w6zld9vxjegxv80mkt6kffgg5enyquqrwnspkqv7sq7v
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMbTJtVVUvaVYvQnZqME1W
            UEJIOHY3OHh6dFNjTEFwSTA3a1FzNHNrYUN3CnhINVNqU1UyMFU0MmEycjZsRllV
            TVNzUlZ1U1YyZm5kVmFWdEJXL2RRVjAKLS0tIEpkZmRqQXFqUjZDaE1QekcrRlNh
            UEkwTk5NOGZSenN6SU80Y2pEQmdxZGsKkGOErpsvdgqWc6rP9Pafh+83j4g29RTi
            1nVo3Gz5Fv4RIItgoe5AHLXIatWV+8hb/hHM8M+kHLCOQyLmZTwH3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k63d5ts2w8hfvdar7lan2qamhcgrjpfdv4um97q0ehjs553x4sysx08xcg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlUEtJbEZ0aFFHVmI1M0Uv
            OHdSMnd4aDc5MWZhZTJCU0ZOcjczaHFLVVdBCk1zTy9XNUdtTm45dWREQ1ArZUND
            WEJOK2pidTFGeGQzeWswLzJWUFg0eWMKLS0tIFpBd0NPYXdLV01pUnV4aFFLNTlS
            TGJzbHA1NGNkSkJzOEdnSnErSUVvRXMKMZXFs8zxMSs/S5GK3BPfQV4JV2IZ96KU
            Cbm1TtS+ATZnr7ok7R9xcnQS5NbOsZV5c8xKOOZpakSwP6K7zmlnVQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mkkltp58ptsvn5t7x8anr4hy20z0z6568nsljfa7tmwx07ug09aqf6rxe6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZGlRZnhtcS8yWjUvVndk
            R0d1QmMzcFd3YkV0YVE5bGt5VS9iUHg1RlFrCmcxRUxQVk5jUysxeDRvSzJaYVpt
            K0hUMHE0L0tGQVcxbFFSVngrZlZWcTgKLS0tIHVtSVVmQ0dDNThkSDd4R1RUU2ww
            MzJlc1FNK1F4dzNRU3kvRWk0NlFGN2sKgCQbACMQXS/FmHmicktt40Q6+2LnmXa5
            v+qqMf0jFk+WvRmK+XabU+p+8GN53JT7qK7roKNhEsim2zlEURB5QA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tfj0kfd2twsa655d5hx2afczlpcfzw7hapc07gr7ywnqq08qxdtsud2gfz
    encrypted_suffix: Templates
    lastmodified: "2026-10-04T03:01:14Z"
    mac: ENC[AES256_GCM,data:fMjACnAFR4tsGoxrPnmJ9Sf/qezwEibtJKOaAVH1aoAaJCY+MyJvmxMEK3uW/2CwBp1+9xgadP7WS4LPCuX2EKxpNJT0WmgHnIIaV3RzYWKUn/wFMPj3srFOmzYK5fougN0abR6SkTSZnYyxfJizm2cVBWMf1aatptI0inFLNMM=,iv:ip/ZTq7O6wOLy8ZhiJne+HCD+0aUc5b8JOjwNnAJZD8=,tag:52q9szNEBJHpMgLl1DUQCA==,type:str]
    version: 3.13.3
