---
deploymentAnnotations:
  reloader.stakater.com/auto: "true"

httpRoute:
  enabled: true
  parentRefs:
      - name: http-gateway
        namespace: envoy-gateway
        sectionName: https
  hostnames:
    - headlamp-h.g4v.dev
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
        - kind: Service
          name: authentik-proxy
          port: 9000
      timeouts:
          request: 0s # websocket, never time out
          backendRequest: 0s # websocket, never time out

image:
  registry: ghcr.io
  repository: headlamp-k8s/headlamp
  tag: "v0.43.0"

config:
  sessionTTL: null
  unsafeUseServiceAccountToken: true
