# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/library/common/values.schema.json
controllers:
  main:
    replicas: 2
    strategy: RollingUpdate
    containers:
      main:
        image:
          repository: ghcr.io/miniflux/miniflux
          tag: 2.3.1-distroless@sha256:6361b075e6189c10f3ac7d18733e467bd3bbf965de2ad5a64a0fb9809456989e
        env:
          BASE_URL: https://miniflux.g4v.dev
          CREATE_ADMIN: "1"
          LOG_DATE_TIME: "1"
          METRICS_ALLOWED_NETWORKS: "10.244.0.0/16"
          METRICS_COLLECTOR: "1"
          FETCHER_ALLOW_PRIVATE_NETWORKSFETCHER_ALLOW_PRIVATE_NETWORKS: "1"
          OAUTH2_USER_CREATION: "1"
          OAUTH2_OIDC_DISCOVERY_ENDPOINT: https://auth.g4v.dev/application/o/miniflux/
          OAUTH2_PROVIDER: oidc
          OAUTH2_REDIRECT_URL: https://miniflux.g4v.dev/oauth2/oidc/callback
          POLLING_SCHEDULER: entry_frequency
          POLLING_FREQUENCY: "15"
          PORT: 3000
          RUN_MIGRATIONS: "1"
        envFrom:
          - secretRef:
              name: miniflux-secret
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthcheck
                port: 3000
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
          startup:
            enabled: false
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
          limits:
            memory: 100Mi
    pod:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        runAsNonRoot: true
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: miniflux

service:
  main:
    controller: main
    ports:
      http:
        port: 3000

route:
  main:
    enabled: true
    parentRefs:
      - name: http-gateway
        namespace: envoy-gateway
        sectionName: https
    hostnames:
      - "miniflux.g4v.dev"
    rules:
      - matches:
        - path:
            type: PathPrefix
            value: /
        backendRefs:
          - group: ''
            kind: Service
            identifier: main
            port: http
            weight: 1

serviceMonitor:
  main:
    enabled: true
    serviceName: 'miniflux'
    endpoints:
      - port: http
        scheme: http
        path: /metrics
        interval: 1m
        scrapeTimeout: 10s
