fullnameOverride: stirling-pdf
nameOverride: stirling-pdf
envs:
  - { name: DOCKER_ENABLE_SECURITY, value: "false" }
  - { name: SECURITY_ENABLE_LOGIN, value: "false" }
serviceMonitor:
  enabled: true
