fullnameOverride: stirling-pdf
nameOverride: stirling-pdf
image:
  repository: stirlingtools/stirling-pdf
  tag: 2.12.0-fat
envs:
  - { name: SECURITY_ENABLELOGIN, value: "false" }
  - { name: FAT_DOCKER, value: "true" }
  - { name: DISABLE_ADDITIONAL_FEATURES, value: "false" }
  - { name: SYSTEM_ENABLEANALYTICS, value: "false" }

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
