serverName: g4v.dev

initSecrets:
  enabled: true

elementAdmin:
  ingress:
    host: element-admin.g4v.dev

elementWeb:
  ingress:
    host: chat.g4v.dev

matrixAuthenticationService:
  annotations:
    reloader.stakater.com/auto: 'true'
  extraEnv:
    - name: RUST_LOG
      value: debug
  ingress:
    host: matrix-mas.g4v.dev
  encryptionSecret:
    secret: matrix-stack-mas
    secretKey: mas_encryption_secret
  synapseSharedSecret:
    secret: matrix-stack
    secretKey: global_registration_shared_secret
  privateKeys:
    rsa:
      secret: matrix-stack-mas
      secretKey: mas_keys_rsa_private
    ecdsaPrime256v1:
      secret: matrix-stack-mas
      secretKey: mas_keys_additional_private_0
    ecdsaSecp256k1:
      secret: matrix-stack-mas
      secretKey: mas_keys_additional_private_1
    ecdsaSecp384r1:
      secret: matrix-stack-mas
      secretKey: mas_keys_additional_private_2
  syn2mas:
    enabled: true
    dryRun: true
  additional:
    1-custom-config:
      configSecret: matrix-stack-mas
      configSecretKey: mas_upstream_oidc.yaml
  postgres:
    host: private-dok8s-sfo2-do-user-8094590-0.b.db.ondigitalocean.com
    port: 25060
    user: matrix-authentication-service-DrutXJ
    database: matrix-authentication-service
    sslMode: prefer
    password:
      secret: matrix-authentication-service-db-secret-matrix-authentication-service
      secretKey: PASSWORD

matrixRTC:
  sfu:
    exposedServices:
      turn:
        enabled: true
  ingress:
    host: matrix-rtc.g4v.dev

synapse:
  annotations:
    reloader.stakater.com/auto: 'true'
  checkConfigHook:
    enabled: false
  image:
    registry: ghcr.io
    repository: halkeye/docker-synapse
    tag: v1.152.0.4
  ingress:
    host: matrix.g4v.dev
  signingKey:
    secret: matrix-stack-synapse2
    secretKey: synapse_signing_key
  macaroon:
    secret: matrix-stack-synapse2
    secretKey: synapse_macaroon_secret_key
  registrationSharedSecret:
    secret: matrix-stack
    secretKey: global_registration_shared_secret
  postgres:
    host: private-dok8s-sfo2-do-user-8094590-0.b.db.ondigitalocean.com
    port: 25060
    user: synapse
    database: synapse
    sslMode: prefer
    password:
      secret: matrix-stack-synapse2
      secretKey: synapse_postgres_password
  additional:
    1-storage:
      configSecret: matrix-stack-synapse2
      configSecretKey: synapse_media_s3.yaml
  ## additional:
  ##   0-customConfig:
  ##     config: |
  ##       <any valid configuration>
  ##   1-customConfig:
  ##     configSecret: custom-config
  ##     configSecretKey: shared.yaml
  ##
  ## Most settings are configurable but some settings are owned by the chart and can't overwritten

  ## Details of Application Service registration files to give to Synapse
  appservices:
    - secret: matrix-stack-appservice
      secretKey: googlechat-doublepuppet.yaml
    - secret: matrix-stack-appservice
      secretKey: googlechat-registration.yaml
    - secret: matrix-stack-appservice
      secretKey: mautrix-gmessages-doublepuppet.yaml
    - secret: matrix-stack-appservice
      secretKey: mautrix-gmessages.yaml
    - secret: matrix-stack-appservice
      secretKey: mautrix-instagram-doublepuppet.yaml
    - secret: matrix-stack-appservice
      secretKey: mautrix-instagram.yaml
    - secret: matrix-stack-appservice
      secretKey: mautrix-linkedin-doublepuppet.yaml
    - secret: matrix-stack-appservice
      secretKey: mautrix-linkedin.yaml
    - secret: matrix-stack-appservice
      secretKey: signal-doublepuppet.yaml
    - secret: matrix-stack-appservice
      secretKey: signal-registration.yaml
    - secret: matrix-stack-appservice
      secretKey: telegram-doublepuppet.yaml
    - secret: matrix-stack-appservice
      secretKey: telegram-registration.yaml
    - secret: matrix-stack-appservice
      secretKey: whatsapp-doublepuppet.yaml
    - secret: matrix-stack-appservice
      secretKey: whatsapp-registration.yaml

wellKnownDelegation:
  enabled: false

postgres:
  enabled: false

hookshot:
  annotations:
    reloader.stakater.com/auto: 'true'
  appserviceRegistration:
    secret: matrix-stack-hookshot
    secretKey: hookshot_appservice
  passkey:
    secret: matrix-stack-hookshot
    secretKey: hookshot_passkey
