---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/library/common/values.schema.json
controllers:
  app:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      app:
        image:
          repository: ghcr.io/chrisms150/kindle-opds-proxy
          tag: 0.1.0
        env:
          TZ: America/Vancouver

service:
  main:
    controller: app
    ports:
      http:
        port: 5000

route:
  main:
    enabled: true
    parentRefs:
      - name: http-gateway
        namespace: envoy-gateway
        sectionName: https
    hostnames:
      - "kindle-opds-proxy.g4v.dev"
      - "kobosync.g4v.dev"
    rules:
      - matches:
        - path:
            type: PathPrefix
            value: /
        backendRefs:
          - group: ''
            kind: Service
            identifier: main
            port: http
            weight: 1
